### ISSUE TITLE
unify all providers to use modules [after TF12]

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#107]
currenlty only libvirt use module

We should unify all provider to same structure

# Dependencies:

- [x] we should do this only after terraform v12

**Comment by MalloZup** [comment]
this is a follow-up from https://github.com/SUSE/ha-sap-terraform-deployments/issues/6

**Comment by MalloZup** [comment]
I'm closing this since we have tracked it on trello

**Comment by diegoakechi** [comment]
Reopening it as it is still relevant.

**Comment by diegoakechi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#107: Refactor the Public Cloud providers to use modules and to follow the same structure as the libvirt provider](https://trello.com/c/SZLu2oTM/855-107-refactor-the-public-cloud-providers-to-use-modules-and-to-follow-the-same-structure-as-the-libvirt-provider)

**Comment by MalloZup** [comment]
@diegoakechi can we close this since we track it already on jira?

**Comment by MalloZup** [comment]
closing as discussed
