### ISSUE TITLE
remove variable running

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#113]
```
variable "running" {
  description = "whether this host should be turned on or off"
  default     = true
}
```

this variable is cosmetical to me. When we deploy a VM we want it always running.

We should keep our codebase KISS and remove it.

@nick-wang @ldevulder @alvarocarvajald any thouhgts on this? do you want to keep it? I would be in favor to remove it, since nobody use it.

**Comment by alvarocarvajald** [comment]
I have not tested the `libvirt` configuration, so no idea of the purpose of the variable. But I agree that it seems unnecessary.

**Comment by nick-wang** [comment]
I have *always* set it as `true`
