### ISSUE TITLE
Jinja variable 'dict object' has no attribute 'monitoring_enabled'

### ISSUE THREAD

**Issue by alvarocarvajald** [SUSE/ha-sap-terraform-deployments#117]
Applying the GCP salted configuration with `init_type = "skip-hana"`, the deployment fails with the following error:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:hana_node' failed: Jinja variable 'dict object' has no attribute 'monitoring_enabled'
```

Checked also with `init_type = "all"`, and the same issue is observed.

**Comment by MalloZup** [comment]
@alvarocarvajald thx for reporting! I will handle it
