### ISSUE TITLE
remove rclone from gcp

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#136]
we should find out a better way of doing this
https://github.com/SUSE/ha-sap-terraform-deployments/blob/e2027f8a7812296d24c3bf8522dc4b34af435917/salt/hana_node/download_hana_inst.sls#L39

**Comment by arbulu89** [comment]
Fixed in: https://github.com/SUSE/ha-sap-terraform-deployments/pull/502
