### ISSUE TITLE
Getting exporter ports from Pillar files instead of hard coded port numbers

### ISSUE THREAD

**Issue by ayoub-belarbi** [SUSE/ha-sap-terraform-deployments#146]
Right now, ports are hard coded in the prometheus.yml file. The best option would be extracting those from the pillar files (clsuter.sls and hana.sls) when monitoring is enabled.

**Comment by MalloZup** [comment]
as discussed we can perhaps evaluaute more later  not hardcoding grains. 

https://github.com/SUSE/ha-sap-terraform-deployments/pull/133

**Comment by MalloZup** [comment]
I think for moment this is nor relatant closing. Feel free to reopen in case
