### ISSUE TITLE
 Manage exporters using systemd and HA. Enable monitoring only for the primary node and remove `monitored_hosts` variable

### ISSUE THREAD

**Issue by ayoub-belarbi** [SUSE/ha-sap-terraform-deployments#147]
Related to #133. Right now, there is a special variable `monitored_hosts` telling which hosts will be monitored. A better approach here is to enable monitoring only for the primary node, assign a virtual ip for each exporter and manage the exporters as a resource managed by HA stack. This will allow us to remove `monitored_hosts` variable.

**Comment by MalloZup** [comment]
we have a variable https://github.com/SUSE/ha-sap-terraform-deployments/blob/c9c4b06a69c425744b6026f39b44e162ec151f3d/libvirt/modules/hana_node/variables.tf#L152

which can disable the exporter by node

**Comment by MalloZup** [comment]
The var got removed closing
