### ISSUE TITLE
rules for hana01?

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#150]
https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/azure/network.tf#L141

is still this valid ? Should we not support just the latest hana?

**Comment by MalloZup** [comment]
@diegoakechi @arbulu89 CC

**Comment by arbulu89** [comment]
@MalloZup the idea is to have HANA 2.0 first, but having HANA 1.0 is a `nice to have` feature, so It should be in our roadmap, obviously without much priority by now.

**Comment by MalloZup** [comment]
Ok. Imho I dunno how "much nice to have" feature we can have.. I think that I would just remove it if possible @diegoakachi. CC.

I'm a minimalist in codebase.  I think if this feature is not really necessary we can remove it... :grin:

**Comment by MalloZup** [comment]
I'm closing for moment since it is lower prio
