### ISSUE TITLE
remove additional_repo and add pkg and add modules

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#152]
# info:

We should remove un-used variables for keep codebase minimal.

This 3 variables at least 2 (add repo and add pkgs) aren't really needed for our use-cases.

The add-modules perhaps

**Comment by MalloZup** [comment]
assigning people for sharing thoughs!

**Comment by MalloZup** [comment]
an historic thing: if we need to introduce `devel_mode` variable this mean that this 2 variable are also more useless then neeeded.

I think in a way encouraging to install pkg is not needed. If people want to add Additional pkgs, they can do later. We should own the control of input.

**Comment by arbulu89** [comment]
I wouldn't remove features that are already tested and working.
In my opinion they don't add much maintenance work and are quite easy to manage.
Removing things is quite tricky as we don't know if anyone is using them. I know that this project is still small and doesn't have users except us, but we always need to think about the impact of these changes.
PD:
The `reg_additional_modules` is in fact used to add PackageHub packages.

**Comment by MalloZup** [comment]
we have removed some of the vars. right now I think this is issue got staled and we can remove vars in future if needed
