### ISSUE TITLE
azure: load balancer rules need a proper name

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#159]
# Description:

we have rules of azure load balance that need to be renamed correctly. 

https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/azure/network.tf#L71

we should not give number names but rather service names which are understanble by human.

`lb_30313` doesn't say anything

# Task

rename all the rule with a service name

**Comment by diegoakechi** [comment]
Closing as per PR https://github.com/SUSE/ha-sap-terraform-deployments/pull/283 where all the namings were adapted to follow the Azure naming guidelines.
