### ISSUE TITLE
ssh keys create step missing in README quickstart

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#163]
At least in libvirt provider [README file](https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/libvirt/README.md), the ssh keys creation step is not mentioned in the quickstart chapter.

The use would need to run:
```
cd salt/hana_node/files
mkdir sshkeys
cd sshkeys
ssh-keygen # Create ssh keys with the name id_rsa_cluster and without passphrase
```

**Comment by MalloZup** [comment]
we don't need to create ssh-key for libvirt

**Comment by MalloZup** [comment]
in the libvirt provider we take the ssh-key avaible form user. In other cloud provider we need to generate them. This was historically implemented, I think it is somehow strange . I think personally we should investigate if we need to create at ALL ssh key for the cloud private providers.

**Comment by MalloZup** [comment]
It might good issue to investigate if we can remove ssh key at all

**Comment by MalloZup** [comment]
If we agee On this approach I would vote to do a research on using shared ssh keys stored somewhere.
So to me the goal of this issue would be to remove the ssh key generation on private clouds, and put the common ssh key I gitlab. We could preserve the ability to the user to create other keys and add them to machines if needed

**Comment by arbulu89** [comment]
@MalloZup, you are right, we don't need the ssh keys for libvirt.
Right now the ssh keys are mandatory for the cloud providers, they are used to enable the communication between the nodes to create the cluster.
The cloud providers nodes are created without password, so in that case we need to use ssh keys to setup the initial communication, otherwise a user interaction is requested.

The truth is that as we have a `quickstart` guide for each provider, and the document is different for all of them I would say they are not properly maintained. For example in Azure, where the keys are needed we don't mention anything about them. I think we should have a unique and generic quickstart guide for the project in the main README.md file.

About using shared ssh keys and store them in some particular repository, I don't see any value on doing that. What's the benefit of copying the files from there to the project instead of creating a new ones?

**Comment by MalloZup** [comment]
the value would be that if for example I deploy a cluster in azure and I need some help, people could log with a shared key..

Libivrt by default read the `users` key. I think why we are not using this approach for cloud provider? I think this should be possible and we remove the creation.

https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/libvirt/modules/hana_node/variables.tf#L54

Imho this should be possible to cloud provider. I might try that out in azure

**Comment by arbulu89** [comment]
This issue is already fixed
