### ISSUE TITLE
Documentation update about workspace name

### ISSUE THREAD

**Issue by juadk** [SUSE/ha-sap-terraform-deployments#169]
We need to precise that the terraform workspace name does not contain `-` or `_ `characters. Otherwise, HANA installation will failed with a "invalid hostname" message.

**Comment by MalloZup** [comment]
@juadk do you have encountered this with azure? afaik in libvirt is not the case.. But yop we can add it to documentation

**Comment by juadk** [comment]
> @juadk do you have encountered this with azure? afaik in libvirt is not the case.. But yop we can add it to documentation

@MalloZup issue encountered today with AWS, @ldevulder told me that it's the same with Azure but I didn't test it myself for the moment.

**Comment by MalloZup** [comment]
fixed bu https://github.com/SUSE/ha-sap-terraform-deployments/pull/205
