### ISSUE TITLE
Consider renaming (or link) AWS and GCP directories

### ISSUE THREAD

**Issue by ldevulder** [SUSE/ha-sap-terraform-deployments#177]
I'm doing some test to be able to execute our Public Cloud test within openQA (to have tests automatically triggered for each new build) and a minor change may be needed to be able to reuse some code from qa-kernel team: they are using 'EC2' for AWS and 'GCE' for 'GCP' (these acronyms are valid), and in our code we use 'aws' and 'gcp' for the directory names.

So could be either rename the directories or add links?

**Comment by MalloZup** [comment]
@ldevulder  yop thx for issue. 

I think renaming this on our side is not a good design choice for 2 reasons:

- aws provider is called `aws` in generic way. not ec2 which is specific to other things.
   same thing apply to GCP

 A renaming will cause lot of issues in code and in infra/scripts on things which rely on this. ( this is more secondary but still relevant in case of work to do).

But I don't think that changing the global api is the goal. I think the good step is to create an adaption in openQA for this. thx for bringing this up anyways :dog:

**Comment by arbulu89** [comment]
@ldevulder What do you exactly want to change? https://github.com/SUSE/ha-sap-terraform-deployments/tree/master/aws and https://github.com/SUSE/ha-sap-terraform-deployments/tree/master/gcp folder names?

**Comment by ldevulder** [comment]
> @ldevulder What do you exactly want to change? https://github.com/SUSE/ha-sap-terraform-deployments/tree/master/aws and https://github.com/SUSE/ha-sap-terraform-deployments/tree/master/gcp folder names?

yes, or either add a link, or as Dario Maiocchi suggested discussed with qa-kernel team to check if they can rename from their side (if all good reasons are write in the issues).

**Comment by juadk** [comment]
I agree with @MalloZup , ask to qa-kernel team if they can rename their stuff, otherwise we could do a code to do the consistency between both aws:EC2 and gcp:GCE.

**Comment by ldevulder** [comment]
I added a function to dynamically link to the corresponding directory in my openQA code, as qa-kernel team used GCE and EC2 because it's the name used by cloud team in their generated images.

Issue closed.
