### ISSUE TITLE
Add option to enable/disable monitoring stack in Azure

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#182]
Right now, the monitoring stack is always deployed in Azure. This must be changed to work as in libvirt, configurable.
We should reuse the `monitoring_enabled` parameter as in libvirt,

**Comment by MalloZup** [comment]
I think the best solution here is to make monitoring a module. 
We can start by the monitoring `module` and that should be ok

**Comment by arbulu89** [comment]
> I think the best solution here is to make monitoring a module.
> We can start by the monitoring `module` and that should be ok

If it's a viable solution it's OK for me. My concern is that if this would request to add a main.tf file and so on... what means not trivial changes. This requires some research.

But the final goal is clear, enable/disable the monitoring stack as wished.

**Comment by ldevulder** [comment]
> If it's a viable solution it's OK for me. My concern is that if this would request to add a main.tf file and so on... what means not trivial changes. This requires some research.

My main concern is just to have a way to do this for 2.2.0 version and not in 6 months if possible :). If it's already available for libvirt (`monitoring_enabled`) why it's not possible to do the same for Azure (and the others PC providers).

The last issue we are facing is that `hanadb_exporter` requires `python3.6` and this version is not installed by default on 12-SP5 PC images, and it's not possible to install it, as this OS is not available on SCC during Build Validation.

**Comment by MalloZup** [comment]
regarding the enabled/disabled we are working on this sprint . so we should have it.

Regarding the python `hanadb_exporter` I think is another issue which we might should track elsewhere and reference it here.

**Comment by juadk** [comment]
Correct me if I'm wrong but from my understand, `monitoring_enabled` doesn't control if you want the monitoring server or not in Terraform. I mean it's just a variable used by salt to load sls files in monitoring folder. Whatever if `monitoring_enabled` is set to `true` or `false`, a monitoring server will be created by terraform. So this variable name is a little confused. WDYT?

**Comment by MalloZup** [comment]
Yep Salt cannot control terraform. The monitoring enabled refer yes to provisions. We need to separate concerns between deployment and provision. We will need to provide different main.tf as inventory of use cases. This is how sumaform solve issue in a easy way. We can just do it same. In a main. Tf without monitoring module the other with

**Comment by ldevulder** [comment]
For sure the monitoring VM shouldn't be provisioning if not needed, as we have to reduce/control costs during our tests and so creating an unneeded VM is not so good ;-)

**Comment by MalloZup** [comment]
@ldevulder regarding the exporter can you open a separate issue and refer to https://github.com/SUSE/ha-sap-terraform-deployments/issues/183. We need to keep track of that. I think it is a serious thing to consider on our release

**Comment by MalloZup** [comment]
Yep I full agree. We should not create the monitor vm by default. This will come this sprint. I will do a pr for libvirt also unless @arbulu89 isn't already on it

**Comment by ldevulder** [comment]
> @ldevulder regarding the exporter can you open a separate issue and refer to #183. We need to keep track of that. I think it is a serious thing to consider on our release

OK, will do it asap!

**Comment by ldevulder** [comment]
Issue #199 for `hanadb_exporter` issue.
