### ISSUE TITLE
RFC: remove `monitoring_hosts` from root tfvars

### ISSUE THREAD

**Issue by stefanotorresi** [SUSE/ha-sap-terraform-deployments#190]
from the followin discussion on RC:

> Stefano Torresi @storresi
> 11:34 AM
> hey folks, I have a question: why are we not just using var.hosts_ip as an input for monitored_hosts in the monitoring tf module? is there any use case at all for wanting to monitor different ips than all the nodes?
> having both hosts_ip and monitored_hosts in the root tfvars, with both always the same values, looks redundant, at first glance
> 
> 
> Xabier Arbulu @xarbulu
> 11:39 AM
> Stefano Torresi Yes, this might be an option. This variable has an history behind. Previously, we added there the address+port to be monitored, by finally It was just changed to address. I guess your point was not considered after that change. But yes, maybe we could remove that parameter now. Dario Maiocchi would be glad to do that XD
> Actually, now I see it. It makes total sense... I guess we want to monitor all the hosts if we enable the monitoring stack. In fact, if some node doesn't have an exporter, it's not harmful anyway

pros:
- one less variable to document
- simpler user-facing api (i.e. the t fvars)

cons:
- less flexibility, I guess?

What's the use case for having these values to be independent?

**Comment by arbulu89** [comment]
I vote to remove that argument. I totally doubt that we will scrape metrics from nodes outside our cluster (does it have any sense)?
In sake of simplicity, it would make things easier.
Opinions @MalloZup , @ayoub-belarbi ?

**Comment by MalloZup** [comment]
Ok for removal. THX

We should add the host ip adress.

**Comment by stefanotorresi** [comment]
apparently the word `address` doesn't trigger automatic issue closure on GitHub, as opposed to GitLab.

**Comment by MalloZup** [comment]
`fix` #number
