### ISSUE TITLE
monitoring_host IP is hardcoded to 1 host

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#193]
We should as discussed remove this hardcode 1 string value for the monitoring_IP.

Instead using a list will allow use to create same host monitoring multiple times.
The count variables is already in place, is just a matter of fixing the IP list

**Comment by arbulu89** [comment]
Hey @MalloZup ,
Why do we need more than one monitoring host? Does this have sense?
This will make everything more complicated when monitoring stack is expanded to the cloud providers.
I would avoid that, and is we deploy the monitoring host, just deploy 1 always.

**Comment by MalloZup** [comment]
@arbulu89  I personally think that having multiples Prometheus is a feature and such conf are allowed upstream
 I don't see personally to much complexity on having the `count` variable.

**Comment by arbulu89** [comment]
For me this is not a complexity matte (but anyway having that is more complex than not having)r, it's about if it makes sense or not. Would the project have any benefit if we deploy several prometheus/grafana servers?
Remember that any of them would have both. So in order to have just multiple prometheus and a unique grafana would require more changes and implementation

**Comment by MalloZup** [comment]
I'm OK to remove it I don't have any strong opinion on this. We can also add it later as counts would not difficult

**Comment by stefanotorresi** [comment]
Well, if it's not clear whether or not this is an actually desired feature, I'd argue for making things simpler and remove it.

On a side note, maybe we should add a list, in the root README, of the features that we are meant to provide and support, leaving less ambiguity and removing the risk of scope creep.

**Comment by MalloZup** [comment]
Ok I think we can remove it then. 

@stefanotorresi  yep. For this sake of things, I'm ok also to add this kind of list of features..

e.g : https://github.com/SUSE/ha-sap-terraform-deployments#major-features is a start. There are also docuemtnation isssue, e.g we want to document the `devel_mode` and `qa_mode` which alter the behaviour. For this.

**Comment by MalloZup** [comment]
I will fix this during the day

**Comment by arbulu89** [comment]
@MalloZup We can close this issue, right?

**Comment by MalloZup** [comment]
@arbulu89 thx for reminder yes
