### ISSUE TITLE
libvirt doesn't set the correct network hostname on the first run

### ISSUE THREAD

**Issue by stefanotorresi** [SUSE/ha-sap-terraform-deployments#197]
**Preface**: this could be an upstream issue; once this is verified, please reference this issue number as soon as work is initiated on the [dmacvicar/terraform-provider-libvirt](https://github.com/dmacvicar/terraform-provider-libvirt) project.

The libvirt provider doesn't seem to correctly use the `hostname` property of `network_interface` blocks in `libvirt_domain` resources.

To reproduce, just try to follow the libvirt README instructions, in particular:

* select a `foo` terraform workspace (ensure its state is empty)
* run `terraform plan`

Expected behaviour:
network hostnames are supposed to be prefixed with `foo`.

Observed behaviour: 
network hostnames are not prefixed with `foo`

If a `terraform apply` is run, then a `plan` is run again, the plan will now inform the user that all the `libvirt_domain` resources will be updated in-place with, among a few other changes that should not be there, the network hostnames now starting with the expected prefix.

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/pull/714
this was fixed
