### ISSUE TITLE
iscsi initiator timeout too large

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#207]
Currently the timeout to wait until an iscsi target is 15000 seconds (more than 4 hours...).
This value looks too large.

https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/hana_node/iscsi_initiator.sls#L26

We should reduce it or add the option to customize that (it would require other extra variable).
I don't know if customization would a good idea (other var in terraform that has to be bypassed to salt).

Opinions?

**Comment by MalloZup** [comment]
to me just a point, OUR CI might be really fast. we should always be geneours with timeout for considering network latency, slow systems out there

**Comment by arbulu89** [comment]
> to me just a point, OUR CI might be really fast. we should always be geneours with timeout for considering network latency, slow systems out there

+4 hours still looks not needed. I wouldn't put more than 1 hour. More if the iscsi server is installed together with the nodes. The nodes installation shouldn't take 1 hour more than the iscsi server... In that case a failure looks the most probable thing, so terraform should fail.

**Comment by stefanotorresi** [comment]
I'd say that if it takes more than 30 minutes to provision the ISCSI host. The slowest to provision are the hana nodes, the iscsi usually only takes a few minutes. This timeout is only related to that.

**Comment by arbulu89** [comment]
Depending on the used provider this might chage (azure has more random provisioning for example). But I agree that the difference it shouldn't be more than 30 minutes, 1 hour at most.
