### ISSUE TITLE
ntpd service is not activated/started on SLE12+

### ISSUE THREAD

**Issue by ldevulder** [SUSE/ha-sap-terraform-deployments#208]
I saw this error in `salt-formula.log`:
2019-09-27 13:01:14,173 [salt.loaded.int.module.cmdmod:397 ][INFO    ][4067] Executing command '/usr/sbin/crm cluster init -y -n hacluster -w /dev/watchdog -i eth0 -u --enable-sbd -s /dev/sdd' in directory '/root'
2019-09-27 13:01:24,002 [salt.loaded.int.module.cmdmod:828 ][ERROR   ][4067] stdout: WARNING: ntpd.service is not configured to start at system boot.

HA stack is working, but it is **definitely** not good as SUSE doesn't support a cluster without `ntpd/chronyd` configured.

Note: it's `ntpd` service in SLE12+, `chronyd` is only available since SLE15.

**Comment by arbulu89** [comment]
Thanks @ldevulder . I will have a look to that!

**Comment by arbulu89** [comment]
Really strange... The service is started and enabled in the habootstrap-formula:
https://github.com/SUSE/habootstrap-formula/blob/master/cluster/ntp.sls#L15

If this failed the salt state should fail.

**Comment by ldevulder** [comment]
I have this with `systemctl status ntpd.service`:
`# systemctl status ntpd.service`
`ntpd.service - NTP Server Daemon`
`   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; disabled; vendor preset: disabled)`
`  Drop-In: /run/systemd/generator/ntpd.service.d`
`           └─50-insserv.conf-$time.conf`
`   Active: inactive (dead)`
`     Docs: man:ntpd(1)`

Another question: is the salt code is supposed to enable the service? I can see it set as `disabled`.

**Comment by juadk** [comment]
@arbulu89 I agree with you but if I understand correctly, ntp.sls is triggered only if cluster.ntp is defined. And it's only the case in [libvirt](https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/pillar_examples/automatic/cluster.sls#L21):

```
  {% if grains['provider'] == 'libvirt' %}
   ntp: pool.ntp.org
```

**Comment by arbulu89** [comment]
@juadk @ldevulder Yes, the issue is not in the formula itself, it's in the pillar...
We will need to update the `automatic/cluster.sls` to enable `ntp` for all the providers.
