### ISSUE TITLE
Manage instance type for monitoring server

### ISSUE THREAD

**Issue by juadk** [SUSE/ha-sap-terraform-deployments#216]
In AWS, I've noticed that we are using the same instance type than HANA node.
FMPOV, it's very overkill. 
In Azure, instance type for monitoring server is hardcoded `vm_size               = "Standard_D2s_v3"`

What do you think? I have 3 solutions in mind:
* hardcoded instance type for monitoring server in AWS
* use iscsi server instance type (which is a small resource) instead of hana instance type
* create a new variable (again...) to define monitoring server instance type

**Comment by MalloZup** [comment]
THX for issue.
I think we can hardcode it and make it more lightweight. I definitely agree it should not be the same of HANA.

 CC @ayoub-belarbi

**Comment by ayoub-belarbi** [comment]
Working on it! Thanks @juadk and @MalloZup

**Comment by stefanotorresi** [comment]
I would say to hardcode it like the iscsi instance, for the time being.
If we want to introduce customization of these parameters, we'd have to disambiguate the current `instancetype` variable and define a common naming convention for all the providers that apply to this kind of customization.

**Comment by MalloZup** [comment]
Fixes
