### ISSUE TITLE
Disable or leave the choice about colors usage in Salt log

### ISSUE THREAD

**Issue by juadk** [SUSE/ha-sap-terraform-deployments#221]
First I understand it is easier to debug with colors in salt log, especially from a customer point of view.
On the other hand, salt log is difficult to read with `vi` or in openQA:
```
[0;32mlocal:[0;0m
[0;36m----------[0;0m
    [0;36m      ID: ha-factory-repo[0;0m
    [0;36mFunction: pkgrepo.managed[0;0m
    [0;36m    Name: ha-factory[0;0m
    [0;36m  Result: True[0;0m
    [0;36m Comment: Configured package repo 'ha-factory'[0;0m
    [0;36m Started: 15:47:43.936692[0;0m
    [0;36mDuration: 4465.307 ms[0;0m
[0;36m     Changes:   
              [0;36m----------[0;0m
              [0;36mrepo[0;0m:
                  [0;32mha-factory[0;0m[0;0m
```
The idea is to replace `--force-color` by `--no-color`.
I think we can leave the choice with a variable but I would not want to add complexity just for that.
That's why I ask your opinion :smiley:
@ldevulder @MalloZup @arbulu89

**Comment by ldevulder** [comment]
As a former sysadmin I don't like the color because it's not easy to grep, real sysadmin doesn't like it :-P
More seriously I understand that some customer may prefer colors by default.

Could it be conditioned by the `qa_mode` variable? By default we can let the color on only add `--no-color` for QA mode.

**Comment by MalloZup** [comment]
I think make sense to have it on `qa_mode` good idea. I would not create another var.

**Comment by juadk** [comment]
Yes it makes sense to be conditioned by the qa_mode variable. Thanks for the feedback!
