### ISSUE TITLE
document pillar for drbd 

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#267]
@nick-wang 
we forget here to add same command like hana

https://github.com/SUSE/ha-sap-terraform-deployments/tree/master/pillar_examples#pillar-examples

something like `/bin/ha-sap-terraform-deployments> cp pillar_examples/automatic/drbd/* salt/drbd_node/files/pillar/`

**Comment by nick-wang** [comment]
@MalloZup I have a sub section `DRBD automatic pillar` in the file. Maybe i need change hana part to the other sub section.

**Comment by MalloZup** [comment]
@nick-wang closing as discussed but send a pr as discussed tia
