### ISSUE TITLE
DRBD to azure related

### ISSUE THREAD

**Issue by nick-wang** [SUSE/ha-sap-terraform-deployments#275]
Some questions/issues about DRBD in azure:

1. The `drbd_disk_device: /dev/sdc`. Is it the same login disk from ISCSI for all drbd nodes? If so, i think need to change to a local volume to DRBD on each node, same ISCSI disk with doesn't qualified as the backing device of DRBD. It needs different devices which usually from different nodes.
So recommend use the disk from same storage pool of drbd node image.

2. Current we are using different partition to sbd for different modules. Like `sbd_disk_device: /dev/sde` for DRBD. Since the SBD support shared between modules, it is also possible or suitable to point to one disk for all modules. So i would recommend use flexible variable to this. 
Could tune this together with the all iscsi related thing if needed.

**Comment by arbulu89** [comment]
Hi @nick-wang 
1. Now, `/dev/sdc` is a local disk and unique for each drbd node
2. We have a quite horrible way of using `iscsi` to be honest. Right now, the iscsi server has a disk attached, that creates 5 partitions by default. The change I did was to server 2 of these partitions in the iscsi service, so the first is used by the hana cluster and 2nd by the drbd cluster (and in my head a 3rd one would be used by NW). I don't really know how we should address this and the recommendations for a production kind deployment.

**Comment by nick-wang** [comment]
@arbulu89 
>     1. Now, `/dev/sdc` is a local disk and unique for each drbd node
That 's great! So it clean my concern.
Now i just curious the (i)scsi discovery orders between local disk and iscsi. 
I will check the code first, will ask you if i have question. Thanks in advanced.

> 
>     2. We have a quite horrible way of using `iscsi` to be honest. Right now, the iscsi server has a disk attached, that creates 5 partitions by default. The change I did was to server 2 of these partitions in the iscsi service, so the first is used by the hana cluster and 2nd by the drbd cluster (and in my head a 3rd one would be used by NW). I don't really know how we should address this and the recommendations for a production kind deployment.

Yes, i saw this in the latest change. I think maybe we can make little improvement for this, though i have some questions for cloud specific need to ask first. (Near an idot of cloud environment)

- A SBD device can be shared between different clusters, as long as no more than 255 nodes.
- One SBD may possible die or need patch update, which cause the cluster incomplete during that time. Though not SPOF. Three SBDs for one cluster is better. 
   Also configuring three SBDs may allow enable diskless SBDs which doesn't require a shared disk.
- SBD devices doesn't need much space. I think 128MB is enough.

So what i purposed after reading the code/azure best practice is:

1. Make SBD partitions smaller, current is 2G.
2. Use same partition for three clusters (HANA/DRBD/NW)
3. Support deploy 3 SBDs per cluster, also shared between HANA/DRBD/NW.
4. Support diskless SBD?

I think the 1 and 2 is quite easy to change as long as we agree with that.
Questions for step 3:
```
1) Do we change it to default or just implement as a option to deploy, cause more nodes (money for customers) needed for multiple ISCSI server.
2) Is that possible to force deploy 3 ISCSI server on different real node in CLOUD environment? Otherwise it doesn't make any sense if it is on the same virtual host. (We could ignore that in `libvirt` provider for test purpose.)
3) Is there a way to control the module deploy/install orders via terraform? (Or maybe it is unnecessary)
   What i want here is we may need to login ISCSI via the uniq ID (only possible to get after ISCSI deployed), so that we could login ISCSI server with ID instead of `/dev/sda`. The later one is not workable due to random orders in multiple ISCSI server environment.
```
For step 4 (diskless SBD), i think we can leave it in the next step with more investigation and testing.

The docs may helpful for the information:
[SBD_Fencing](http://www.linux-ha.org/wiki/SBD_Fencing)
[SUSE azure with 3 SBDs](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker)

**Comment by nick-wang** [comment]
@diegoakechi 
Sorry for the long writing here, this is the reason i want to find a time to discuss the details and ask the question before send a pull request.

It seems neither not suitable to be raised on HA global call nor RC, where i always cause noise. Also i think RC is not suitable for a discussion instead of a specific question. When do you usually discuss things like that, in stand-up meeting or arrange a call on demand?

**Comment by arbulu89** [comment]
@nick-wang Can we close this ticket?
It's clear that we need to work on how we use iscsi disks and sbd configuration.
In the last discussions, the overall comments were that it would be convenient to use different disks for each cluster (but maybe we could have the option to use both options depending on the user input). Besides that, we need to improve how we use the iscsi formula and if possible use the same formula to run the initiator and only discover the disk that will be used for this cluster instead of all of them.
