### ISSUE TITLE
DRBD panel data shown in all the cluster

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#278]
DRBD panel data shown in all the cluster, so it's not filtered by job.
We should filter that to don't create confusion.

And we can just update the headers to start with upper case

![image](https://user-images.githubusercontent.com/36370954/69821991-09fa0600-11fd-11ea-9400-b45d5a05a81a.png)

**Comment by MalloZup** [comment]
@arbulu89 thx!
