### ISSUE TITLE
The disks should be mounted by UUID

### ISSUE THREAD

**Issue by diegoakechi** [SUSE/ha-sap-terraform-deployments#288]
As a good practice, all the disks (local or from iSCSI) should be mounted based on its UUID on the `/etc/fstab` instead of the device path (eg. `/dev/sda`), as this path can chance in case of reboot or disk reallocation.

**Comment by arbulu89** [comment]
Closing the ticket. The disks are mounted using the UUID since some time ago. If we find some specific disk that is not attached we will open a dedicated issue
