### ISSUE TITLE
Azure: LB rules should dynamically choose the port based on the instance number

### ISSUE THREAD

**Issue by diegoakechi** [SUSE/ha-sap-terraform-deployments#295]
This is a follow-up issue for this PR https://github.com/SUSE/ha-sap-terraform-deployments/pull/292

The HANA ports need to follow the instance number: 3xx13, 3xx14, 3xx15, 3xx17 where xx is the instance number. Same for health probe, which is 625xx.

The terraform scripts should dynamically calculate that based on the Instance Number informed for the installation and properly create the LB Rules. 

More details can be found on the link: https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-high-availability

**Comment by arbulu89** [comment]
This feature is already implemented. Here one of the involved commits:
https://github.com/SUSE/ha-sap-terraform-deployments/commit/4bee4225b39a0241a87ffaad9cb0cc0772f15ba1
