### ISSUE TITLE
Add resource type to the resources table

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#315]
I miss the resource type in the table with the information of the resources.

![image](https://user-images.githubusercontent.com/36370954/72244648-0248c200-35ef-11ea-8c72-24b2b71bccc2.png)

Could we add a new column showing the resource type?

As far as I checked there is not such an information in our current metrics of the `ha_cluster_exporter`, so it should be implemented.

**Comment by MalloZup** [comment]
@stefanotorresi is this done?

**Comment by stefanotorresi** [comment]
yes, this will be closed automatically as soon as develop is merged into master.

**Comment by MalloZup** [comment]
ok update the jira card associated then .tia :floppy_disk:

**Comment by MalloZup** [comment]
closing as done see comments.
