### ISSUE TITLE
feature request: apply SAP kernel update

### ISSUE THREAD

**Issue by bjin01** [SUSE/ha-sap-terraform-deployments#327]
Customer requesting possibilities to automate SAP kernel update and saphostagent update.
In order to achieve the current sap kernel version must be obtained at the first. saphostctrl executed as root is providing such information. 
With the obtained sap kernel version the next step is jumping to the correct SAR file which is often made available via NFS on the respective host.
SIDADM is another parameter that needs to be obtained or provided through pillar, grains or obtained from saphostctrl
Then final step is issuing the correct update command as SIDADM.

Has anyone tried to do it or thought about how to achieve? Unfort. there is no python lib for obtaining all the information except by using saphostctrl as binary.

**Comment by Simranpal** [comment]
I think for this we would need to add the functionality in our current python shaptools project to run the `saphostexec` , `SAPCAR` commands and correspondingly create new salt logic to automate the steps of copying, start/stop, backup, setting permissions for kernel files

**Comment by arbulu89** [comment]
Hi @bjin01 , I just found this ticket now... sorry for not attending it before...

I don't really see how we can implement your proposal. You are talking about an upgrade, and we only do a pure new installation. Does it make any sense to upgrade the kernel in a newly installed environemtn?
I don't know if adding such a feature in this project is a good idea. What do you think @diegoakechi ?

Apart of that, we could help creating salt states for the requirements you have and even add them to the `saphanabootstrap-formula` and `sapnwbootstrap-formula`.

**Comment by yeoldegrove** [comment]
We will not implement this for now.
