### ISSUE TITLE
DRBD server: why using iSCSI LUNs?

### ISSUE THREAD

**Issue by ldevulder** [SUSE/ha-sap-terraform-deployments#354]
I saw that the DRBD server in Azure (and I think in libvirt also) is using LUNs provided by the iSCSI server, but what is the reason for this?

We could use a data disk on each DRBD server on do the sync on these disks. Data will still be duplicated and the DRBD service as well as the DRBD service. And this could increase the I/O performance (if needed).

And as the iSCSI server is not configured with HA we have a SPOF here (this is true for HANA server I know ;-) so this is something that we have to address in the future).

**Comment by ldevulder** [comment]
In fact it seems that I miss something during my first read (I first focused on the salt provisioning file). I can see a `storage_data_disk` for drbd data in `modules/drbd_node/main.tf`, so I can close this issue (and slap!) myself.

**Comment by diegoakechi** [comment]
@ldevulder no problem... Thanks for caring... ;)
