### ISSUE TITLE
Unify design with `pillar` between hana and netweaver

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#355]
We have right now:

https://github.com/SUSE/ha-sap-terraform-deployments/tree/master/salt/netweaver_node/files/pillar

which are direct on the node (not configurable)

For `hana` we have `pillar_example` dir,  which is configurable by user.
https://github.com/SUSE/ha-sap-terraform-deployments/tree/master/pillar_examples

We should unify the design, either by moving the netweaver in `pillar_example` dir like hana and make them configurable . ( this is imho the most logic/coherent solution)

**Comment by arbulu89** [comment]
@MalloZup This issue was fixed in https://github.com/SUSE/ha-sap-terraform-deployments/commit/b6555bbe8746f9b4f41b82e81cb64c9aa9f9de32#diff-f272db2f00810f6e8a7dd26fb8269a6c
