### ISSUE TITLE
[libvirt]: Terraform destroy fails 

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#374]
# Description:

When we have the cluster creation on libvirt failing for X reason and lead the cluster to a broken status, sometimes we have this error when doing `terraform destroy`

```
 Error: Invalid index
  on modules/netweaver_node/main.tf line 75, in output "output_data":
  75:     addresses         = libvirt_domain.netweaver_domain.*.network_interface.0.addresses.0

The given key does not identify an element in this collection value.
```

So we can't destroy anymore correctly the cluster unless we do it with virsh or other `non` terraform methods

**Comment by Simranpal** [comment]
Hi @MalloZup does specifying the tf vars file with `terraform destroy` help

**Comment by MalloZup** [comment]
closing for moment since I can't reproduce
