### ISSUE TITLE
Alert.yaml file should be plenty data only

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#386]
https://github.com/SUSE/ha-sap-terraform-deployments/commit/07952934aad8f405d40890c00ad4e9cf7d110108

we should remove `raw` so user can copy and paste directly

**Comment by arbulu89** [comment]
Fixed in https://github.com/SUSE/ha-sap-terraform-deployments/commit/a850f875af4a555d59689691388554e670084a56#diff-b142ce7cc6d6c819cbe52ebe1deadbce
