### ISSUE TITLE
FEATURE request (AWS)

### ISSUE THREAD

**Issue by picoroma** [SUSE/ha-sap-terraform-deployments#402]
Do you have in the pipeline to deploy this scenario into a pre-existing VPC ?
If, yes - when ?
THX in advance

**Comment by arbulu89** [comment]
Hi @picoroma,
Thanks for the ticket. Yes, it's in our backlog, but we are not going to work on it most probably the next month at least.

PD:
About using an existing VPC, consider that for that terraform needs to import all the information from AWS. At this point, terraform will store all the state, so we assume that the resource is managed by terraform now on. This means that any manual change in the VPC, will put the project out of sync, in an unstable situation. 

Just warming you that using terraform with existing resources can have some side-effects.

**Comment by arbulu89** [comment]
Hi @picoroma . I will start working on this task now. I have a question.
Besides the VPC, do you have in mind any other resource that you would like to reuse (already created resources)?
I don't know, the security group, subnets, etc

**Comment by picoroma** [comment]
Subnet could be fine.SG also, but less important I mean...Il 17 apr 2020 15:14, Xabier Arbulu Insausti <notifications@github.com> ha scritto:
Hi @picoroma . I will start working on this task now. I have a question.
Besides the VPC, do you have in mind any other resource that you would like to reuse (already created resources)?
I don't know, the security group, subnets, etc

**Comment by arbulu89** [comment]
@picoroma Forget about that hehe, When I wrote it I didn't have all the knowledge. Now I know that we can use an already existing VPC without any risk.

**Comment by picoroma** [comment]
👍Let me know when is possible to test itP.

**Comment by arbulu89** [comment]
Issue fixed. It will be available in version `5.0.0`
