### ISSUE TITLE
Problem deployng complete stack (HANA & NW)

### ISSUE THREAD

**Issue by picoroma** [SUSE/ha-sap-terraform-deployments#404]
Hi!
After the complete deploy of HANA cluster I uncomment the line to deploy the complete stack.
I have observed that it creates 4 NW AS.
Anyway, the deploy do not finished after 10 h and I have stopped.
The problem seems that when should start the "sapinst" part, nothing happens and the log do not report any update.
sapinst_instdir is empty
swpm_unattended folder is empty

Nothing was created into /usr/sap/HA1 - except for some folder (ASCS etc)
In the salt-formula.log file the latest info are:

2020-03-26 16:02:31,935 [shell            :143 ][DEBUG   ][9528] Executing command "printf '%q ' /tmp/swpm_unattended/*" with user root
2020-03-26 16:02:31,935 [shell            :151 ][DEBUG   ][9528] Command updated to "su -lc "printf '%q ' /tmp/swpm_unattended/*" root"
2020-03-26 16:02:31,979 [shaptools.shell  :53  ][INFO    ][9528] /tmp/swpm_unattended/start_dir.cd 
2020-03-26 16:02:31,979 [shell            :143 ][DEBUG   ][9528] Executing command "rm -rf  " with user root
2020-03-26 16:02:31,979 [shell            :151 ][DEBUG   ][9528] Command updated to "su -lc "rm -rf  " root"
2020-03-26 16:02:32,022 [shell            :143 ][DEBUG   ][9528] Executing command "/netweaver_inst_media/sapinst/sapinst SAPINST_USE_HOSTNAME=sapha1as SAPINST_EXECUTE_PRODUCT_ID=NW_ABAP_ASCS:NW750.HDB.ABAPHA SAPINST_SKIP_SUCCESSFULLY_FINISHED_DIALOG=true SAPINST_START_GUISERVER=false SAPINST_INPUT_PARAMETERS_URL=/tmp/ascs.inifile.params SAPINST_CWD=/tmp/swpm_unattended" with user root
2020-03-26 16:02:32,023 [shell            :151 ][DEBUG   ][9528] Command updated to "su -lc "/netweaver_inst_media/sapinst/sapinst SAPINST_USE_HOSTNAME=sapha1as SAPINST_EXECUTE_PRODUCT_ID=NW_ABAP_ASCS:NW750.HDB.ABAPHA SAPINST_SKIP_SUCCESSFULLY_FINISHED_DIALOG=true SAPINST_START_GUISERVER=false SAPINST_INPUT_PARAMETERS_URL=/tmp/ascs.inifile.params SAPINST_CWD=/tmp/swpm_unattended" root"

And after that. Nothing more, even after 8h waiting...
P.

**Comment by diegoakechi** [comment]
Hi @picoroma,

Can you please check the following steps:

 That you have these variables properly configured on your tfvars and the SAP NW binaries available in a shared bucket similar you have with HANA?
```
netweaver_enabled      = true
netweaver_instancetype = "r3.8xlarge" 
netweaver_s3_bucket    = "s3://<your path>"
netweaver_ips          = ["10.0.2.7", "10.0.3.8", "10.0.2.9", "10.0.3.10"]
netweaver_virtual_ips  = ["192.168.1.20", "192.168.1.21", "192.168.1.22", "192.168.1.23"]
```
Also that you have adapted the Netweaver Pillar file with the location for the SWPM, SAP Kernel, and Additional DVDs that you want to install?

https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/netweaver_node/files/pillar/netweaver.sls#L27

**Comment by picoroma** [comment]
The S3 bucket shoul be OK. Regarding the VM Size I have choose - VM smaller (r3.xlarge)
Pillar file should be OK also. But I double check it.

**Comment by arbulu89** [comment]
@picoroma Some question.
What happens if you access the machine and run the posted command manually? What is the output?
I guess that `/netweaver_inst_media/sapinst/sapinst` exists, right? 
And, could you check what do you have in `/netweaver_inst_media` ? This folder should contain the all the components you have in the used S3 bucket link.
So, based in that, the `neweaver.sls` file should use the folder names of that S3 bucket.

**Comment by picoroma** [comment]
I'm trying to deploy with NW.
After the HANA DB creation.
The deploy loop into thist message log:

module.netweaver_node.null_resource.netweaver_provisioner[3]: Still creating... [41m34s elapsed]
module.netweaver_node.null_resource.netweaver_provisioner[1]: Still creating... [41m34s elapsed]
module.netweaver_node.null_resource.netweaver_provisioner[2]: Still creating... [41m33s elapsed]
module.netweaver_node.null_resource.netweaver_provisioner[0]: Still creating... [41m32s elapsed]
module.netweaver_node.null_resource.netweaver_provisioner[2] (remote-exec): [INFO    ] Running state [/sapmnt/HA1/profile] at time 15:14:32.377997
module.netweaver_node.null_resource.netweaver_provisioner[2] (remote-exec): [INFO    ] Executing state file.exists for [/sapmnt/HA1/profile]
module.netweaver_node.null_resource.netweaver_provisioner[2] (remote-exec): [ERROR   ] Specified path /sapmnt/HA1/profile does not exist
module.netweaver_node.null_resource.netweaver_provisioner[2] (remote-exec): [INFO    ] Completed state [/sapmnt/HA1/profile] at time 15:14:32.379642 (duration_in_ms=1.647)
module.netweaver_node.null_resource.netweaver_provisioner[2] (remote-exec): [INFO    ] State result does not match retry until value, state will be re-run in 30 seconds

Seems that /sapmnt/HA1/profile - do not exist even if the  EFS is correctly mounted:

ec2-user@netweaver01:/sapmnt> df -h
Filesystem                                             Size  Used Avail Use% Mounted on
devtmpfs                                                15G  8.0K   15G   1% /dev
tmpfs                                                   24G     0   24G   0% /dev/shm
tmpfs                                                   15G   17M   15G   1% /run
tmpfs                                                   15G     0   15G   0% /sys/fs/cgroup
/dev/xvda1                                              60G  5.1G   55G   9% /
tmpfs                                                  3.0G     0  3.0G   0% /run/user/1000
fs-5cf45.efs.eu-central-1.amazonaws.com:/sapcd      8.0E     0  8.0E   0% /netweaver_inst_media
fs-5cf45.efs.eu-central-1.amazonaws.com:/sapmnt     8.0E     0  8.0E   0% /sapmnt
fs-5cf45.efs.eu-central-1.amazonaws.com:/usrsapsys  8.0E     0  8.0E   0% /usr/sap/HA1/SYS
fs-5cf45.efs.eu-central-1.amazonaws.com:/ASCS       8.0E     0  8.0E   0% /usr/sap/HA1/ASCS00

**Comment by arbulu89** [comment]
@picoroma The NW installation folders should be available in `/tmp/swpm_unnattended`. So, do we have any kind of logs there. Anything.
This loop is there because ASCS should be being installed, and this instance created the content for that folder. The other instances are just waiting for it.

Try to see if this file is available: `/tmp/swpm_unnattended/sapinst.log`. 
Finally, try again to run the command manually, this will give you more information about what's failing.

**Comment by picoroma** [comment]
/tmp/swpm_unnattended/ - is empty!!

**Comment by arbulu89** [comment]
@picoroma Did you try to run the SWPM command manually? This would help to know what's going on there

**Comment by arbulu89** [comment]
@picoroma Without more information, I will close the ticket, as there is nothing we can do.
