### ISSUE TITLE
Please ADD the un-registration of SUSE Server subscription before "destroy"

### ISSUE THREAD

**Issue by picoroma** [SUSE/ha-sap-terraform-deployments#405]
[FEATURE] Due to some SUSE subscription limit, is usefull to add the un-registration of the VM involved - before to perform the undeploy of the stack (terraform destroy).

**Comment by diegoakechi** [comment]
@picoroma This is a good idea... We will include in our backlog for future implementations.

**Comment by arbulu89** [comment]
@picoroma The feature has been implemented in #412. It will be released in the next version (`5.0.0` most probably) that will come soon, in some few weeks.
