### ISSUE TITLE
Reformat project documentation - Variables chapter

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#415]
Hello,
I would like to raise a question about our documentation. Specifically this chapter:
https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/aws/README.md#specification
(for all the providers, obviously).

I'm wondering, if we should continue adding there the project variables. I think that we are duplicating information. I would just forward the documentation to the main `variables.tf` file. That terraform files are meant to be self explicative. In fact, it would make us to work more on the descriptions there.

What do you think guys?
@diegoakechi @MalloZup @stefanotorresi @Simranpal @ldevulder @juadk

**Comment by diegoakechi** [comment]
@arbulu89 I agree, as soon as we include meaningful descriptions there =)

**Comment by juadk** [comment]
@arbulu89 yes, the variables list is starting to be too long. I agree if we can put a link and descriptions in `README` file for each provider to their own `variables.tf.`

**Comment by stefanotorresi** [comment]
I second @juadk!

**Comment by MalloZup** [comment]
perhaps @juadk  proposition could save an additional page of documentation so I tend to like that, because the documentation could be enforced and tied more close to code re-visioning.
