### ISSUE TITLE
Refactoring: consolidate reg_code and reg_user to a map

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#436]
This is a small fix. We should instead of have 2 variable, use a map.

https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/libvirt/variables.tf#L121

```
variable "credentials" {
  type = "map"
   default = {
    reg-code  = "bra"
    reg-mail    = "foo"
   }
```

In this way it is more compact and consistent

**Comment by arbulu89** [comment]
I don't see why this is more consistent. The maps are used when you have multiple possible entries. Here we only have one. Why do we need a map?

**Comment by MalloZup** [comment]
It would fit the vars in namespace, but is not a urgent refactoring, and we have more important closing
