### ISSUE TITLE
FEATURE Request - Deployment of S/4HANA in addiction to Netweaver

### ISSUE THREAD

**Issue by picoroma** [SUSE/ha-sap-terraform-deployments#441]
Hi!
Are you planning to add additional SAP products deployment with these script like S/HANA or BW/4HANA for example ?
I think  that the process shoulb be very similar.
THX
P.
PS: I still have to finish correctly the deploy of Netweaver :-)

**Comment by arbulu89** [comment]
@picoroma The implementation for S/HANA is already done. The unique thing we need to do is to configure the deployment properly.
To use S/HANA, you will need to change the value of `netweaver_product_id` in the terraform.tfvars.
For example `netweaver_product_id=S4HANA1709.CORE.HDB.ABAPHA`.
Besides that, you will need to make a change in the `netweaver.sls` pillar file that is available at `pillar_examples/automatic/netweaver` where you will need to enable `NW_liveCache.useLiveCache: "false"` flag in the `PAS` (now it's commented, you will need to uncomment) and `attempts: 500` in the `AAS`.

We aware that S/HANA deployment is extremely long (it might take more than 5 hours easily).

**Comment by picoroma** [comment]
Hi! THX a lot.
Can you detail more the structure of S3 bucket that is expected in order to deploy S/4HANA.
How the .SAR files have to be provided.
In a compressed or uncompressed way.
And the exact list of expected files ?
Another question. For testing porpouse is possible to deploy a "small" enviroment with 1 HANA DB and 1 NW AS.
The default deploy need of 8 VM (2 DB - 4 AS and 2 VM more) !
THX

**Comment by arbulu89** [comment]
@picoroma 
For the 1st question. You need to have this folders in your storage buckets (S3 for AWS). The versions of the components can be different.
SWPM - `IND:SLTOOLSET:2.0:SWPM:*:LINUX_X86_64:*x`
S4HANA Export - `SAP:S4HANA:1709:DVD_EXPORT:S4HANA OP 102 Installation Export DVD 1/1:BD51052190`
HANA Platform- `HDB:HANA:2.0:LINUX_X86_64:SAP HANA PLATFORM EDITION 2.0::BD51053787`
Kernel files:
```
igsexe_23-20007790.sar  igshelper_4-10010245.sar  SAPEXE_501-80002573.SAR  SAPEXEDB_501-80002572.SAR  SAPHOSTAGENT45_45-20009394.SAR
```

For the 2nd question, by now there is not a straightforward option to deploy the scenario you suggest (one HANA machines and 1 NS ASCS machine). Anyway, this can be done changing some code of the implementation.
In the next week we plan to release the version `5.0.0`, but this release will not provide what you ask.
We will work on that next, so what you want might come in next version (`6.0.0` or `5.X.X`).

**Comment by picoroma** [comment]
Hi ! As per your answer, the Kernel should be provided i a separated SAR file and not in a Entire CD\DVD ?
Right ?

**Comment by arbulu89** [comment]
> Hi ! As per your answer, the Kernel should be provided i a separated SAR file and not in a Entire CD\DVD ?
> Right ?

Yes, basically the kernel is a folder that stores these SAR files. It's not kernel itself, a group of software basically, but SAP uses this terminology to ask for these tools.

**Comment by arbulu89** [comment]
S4/HANA deployment is already available using the correct configuration

**Comment by picoroma** [comment]
Hi Xabi!
Do you have support also for not HA scenario ?
I mean an S4 with DB Server and Application Server (without HA)?
THX

**Comment by arbulu89** [comment]
> Hi Xabi!
> Do you have support also for not HA scenario ?
> I mean an S4 with DB Server and Application Server (without HA)?
> THX

Yes!
In any case, by now, it will be always composed by 3 machines.
- 1 machine for the HANA database
- 1 machine for the application message server (ASCS)
- 1 machine for the application (PAS)

It's a matter of configuration. We need to play with the next parameters:
```hana_ha_enabled = false
netweaver_ha_enabled = false
# And use the correct product id for S4/HANA (obviously, we need to select the desired version)
netweaver_product_id = "S4HANA1909.CORE.HDB.ABAP"
```
