### ISSUE TITLE
SAP HANA HA operating on Azure - Corosync configurations

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#453]
Hi, 

Azure team tunes the `/etc/corosync/corosync.conf` configurations file to have some non-default values as stated in [Cluster installation](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#cluster-installation) -> step #14.

The current generated Corosync configurations file using this project doesn't follow the above-mentioned recommended Azure tuned values.

Here is my current generated `/etc/corosync/corosync.conf` file:
```
vmhana01:~ # cat /etc/corosync/corosync.conf
# Please read the corosync.conf.5 manual page
totem {
	version: 2
	secauth: on
	crypto_hash: sha1
	crypto_cipher: aes256
	cluster_name: hana_cluster
	clear_node_high_bit: yes
	token: 5000
	token_retransmits_before_loss_const: 10
	join: 60
	consensus: 6000
	max_messages: 20
	interface {
		ringnumber: 0
		mcastport: 5405
		ttl: 1
	}

	transport: udpu
}

logging {
	fileline: off
	to_stderr: no
	to_logfile: no
	logfile: /var/log/cluster/corosync.log
	to_syslog: yes
	debug: off
	timestamp: on
	logger_subsys {
		subsys: QUORUM
		debug: off
	}

}

nodelist {
	node {
		ring0_addr: 10.74.1.11
		nodeid: 1
	}

	node {
		ring0_addr: 10.74.1.12
		nodeid: 2
	}

}

quorum {

	# Enable and configure quorum subsystem (default: off)
	# see also corosync.conf.5 and votequorum.5
	provider: corosync_votequorum
	expected_votes: 2
	two_node: 1
}
```

Notice the different values for `token` and `consensus` parameters.

Please update the Corosync configurations to match the Azure ones.

Best regards,
Ab

**Comment by diegoakechi** [comment]
Hi @ab-mohamed 

It is already implemented on the Develop branch. Basically on the next release (5.0.0) you will be able to set pillar entries for the Corosync configuration. 

The automatic pillars will bring the Azure parameters set by default. For reference:

https://github.com/SUSE/ha-sap-terraform-deployments/blob/develop/pillar_examples/automatic/hana/cluster.sls#L30

**Comment by diegoakechi** [comment]
Closing it as it is solved and the release is close. Re-open if you find anything else needed.

Regards,
