### ISSUE TITLE
Redefine qa_mode flag usage

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#463]
I want to open a RFC here to discuss about the `qa_mode` flag usage.

So, right now, the flag is used for:
- Remove colored output of salt result
- Avoid packages installation
- Run hwtcc tests in hana nodes at the end of the deployment

I would like to remove the `qa_mode` as it's a mix of different things, that makes the implementation more difficult. With that said, **I don't pretend to remove the functionalities, just how they are used**.

So my suggestions would be:
- Add a new flag for `salt_force_color` that is used to choose whether colored or not colored output

- Add a new flag to avoid the packages installation, something like `offline_mode`. With that we would avoid the SCC registration and any other new repository addition. **But we are not going to skip any package installation!** This way, salt would try to install the packages, and as the method is idempotent, if it's installed, it would continue, otherwise it would install the packages. This approach is better, because the code is easier, and I think it covers all the use cases we want. Because if the packages are not coming in the image and we run with `qa_mode`, the deployment will logically fail, and this is normal.

- Change the `hwcct` flag usage to just work independently of `qa_mode` or any other flag. If it's `true` the operations are executed, not otherwise. In fact, if `hwcct` is something that more users might be interested on running to certify the installation, we might add it in the formula itself.

With these 3 changes, we could remove this quite ugly `qa_mode` and make everything more logical.

What do you think guys? 
@diegoakechi @ldevulder @juadk @MalloZup

**Comment by MalloZup** [comment]
@arbulu89 make sense for me, good refactor since It make the code more readable and less obscure.

On the same road, we should remove `devel_mode` variable and make new vars of it

**Comment by juadk** [comment]
@arbulu89 I agree with you. I'm not against that, however, if we need to add another specific thing for QA, we will have to add another flag less generic than `qa_mode`, I mean small actions like disable color output. This is the only drawback from my point of view.

**Comment by ldevulder** [comment]
@arbulu89 Sounds good for me! As @juadk mentioned doing this can lead us to add new variables in the future instead of only having `qa_mode`. But in the same time it's more tunable.

**Comment by arbulu89** [comment]
@juadk @ldevulder Thanks for your response. I see that this new potential implementation wouldn't break anything in your side. So, I see it as `green` light.

About adding new features for `qa`, I still say that this project cannot be oriented to be used as a testing tool. It's purpose is to deploy SAP environments. Any new feature must be oriented in that sense. We cannot continue adding features because you need them to do build validations. This doesn't mean that you cannot use the deployed environment to run your tests later, but this should be done using other methods, not the project itself.

Now on, we need to carefully think the new features addition, as the project will reach a point where it will be supported and maintaned officially in SLE releases, so the strategy must be totally oriented for that.

**Comment by ldevulder** [comment]
> We cannot continue adding features because you need them to do build validations. This doesn't mean that you cannot use the deployed environment to run your tests later, but this should be done using other methods, not the project itself.

We were asked by our manager to use this tool to do QA, but they don't asked us to do the QA of the tool itself (not yet, as already discussed with @diegoakechi this part should be seen with management). So if we can add specificities to do the Build Validation then we should use another method to do our QA stuff.

@diegoakechi It's not the good place to discuss this: but please as I already said check this with our Team Lead/Automation Lead/Project Manager! This needs to be cleared :-)

**Comment by diegoakechi** [comment]
@ldevulder I will. As you said, this is not the right place for this discussion, so I will not comment on here.
