### ISSUE TITLE
Align VM size for DRBD on all providers

### ISSUE THREAD

**Issue by ldevulder** [SUSE/ha-sap-terraform-deployments#466]
`t2.micro` is used for AWS, which is a VM with 1 vCPU and 1 GB of RAM, while `n1-standard-4` is used for GCP (4 vCPUs and 15GB of RAM) and `Standard_D2s_v3` for Azure (2 vCPUs and 8GB of RAM).

Could be better to have the same kind of default VM for all providers, no?

As some power may be needed on the DRBD cluster maybe we can use `Standard_D4s_v3` for Azure, `t2.xlarge` for AWS and `n1-standard-4` for GCP? All providers should pretty much have 4 vCPUS and ~16GB of RAM.

**Comment by MalloZup** [comment]
@ldevulder  is the PR linked fixing this? TIA

**Comment by yeoldegrove** [comment]
@arbulu89 Do you think this is still valid to change?
To not be "too expensive" in the default setup, one could also use 2 vCPUs and ~8GB RAM as the default.
For production setups one has to consider the actual workload anyhow.

**Comment by yeoldegrove** [comment]
DRBD is not that of an priority right know.
