### ISSUE TITLE
Monitoring: dashboard variable dc_instance need improvements

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#467]
# Description:

We have a timeframe where on a ha cluster dashboard where we loose data showed on dashaboard.

I found out that after rebooting the var `dc_instance` is unstable, pacemaker doesn't set it all the time. Especially when the node is rebooting/recovering.
So since we use this variable as switcher for dashboard "Ha cluster details", we have a situation when the user is trying to dive in on details why for example has reboot,

# How to reproduce:

1) reboot a hana node
2) check the details 

# expected behaviour:

we should continue to visualize data

**Comment by arbulu89** [comment]
@MalloZup I'm closing this ticket. So far, I don't see this behaviour. The switcher on the `ClusterLabs HA Cluster details` dashboard is retrieved from the configured prometheus jobs, so it is static.
And when a machine is rebooted, the dashboards report that one node is offilne, but after coming back everything gets back to normality
