### ISSUE TITLE
Multi-AZ setup 

### ISSUE THREAD

**Issue by weikiat8** [SUSE/ha-sap-terraform-deployments#472]
Possible to have multiple AZ deployment for HANA and S/4 on AWS, Azure and GCP? to provide higher reliability and availability

**Comment by arbulu89** [comment]
> Possible to have multiple AZ deployment for HANA and S/4 on AWS, Azure and GCP? to provide higher reliability and availability

Hi @weikiat8 ,
Could you elaborate more about this request? What do you mean by `multi-az`?
Multiple availability sets/zones?

This is already available (at least in `devel` branch, which we are going to merge to master soon).

- Azure: The clustered machines are inside an availability set (this means different zones/racks inside the regions)
- GCP/AWS: The machines are in different availability zones

**Comment by weikiat8** [comment]
Cool @arbulu89 , yes i'm referring to `multi-az`. i ran the GCP deployment using master branch, saw the deployments are in single AZ, if it will merge to master soon then i'll wait. Cheers!

**Comment by arbulu89** [comment]
> Cool @arbulu89 , yes i'm referring to `multi-az`. i ran the GCP deployment using master branch, saw the deployments are in single AZ, if it will merge to master soon then i'll wait. Cheers!

Hi @weikiat8 ,
That's strange, even in master branch the HANA machines in GCP are deployed in different availability zones.

https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/gcp/instances.tf#L49

The `count.index` changes the used availability zone for each machine of this type.

The same concept applies for the machines created in AWZ and Azure
