### ISSUE TITLE
The SUSEConnect -d command fails in AWS with Netweaver nodes 3 and 4

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#474]
The SUSEConnect -d gets blocked during the `on_destroy` stage in AWS in the NW nodes 3 and 4.

Only happens here. If you run `SUSEConnect -d` manually, you can notice that the command gets blocked.

In order to workaround this and at least destroy the AWS resources, "generic_modules/on_destroy/main.tf" has been changed to add a timeout in the destroy command.

You will find this error log after this workaround:

```
#<Thread:0x000055d2e7e61e18@/usr/lib64/ruby/2.5.0/open3.rb:264 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /usr/lib64/ruby/2.5.0/open3.rb:264:in `block (2 levels) in capture3'
/usr/lib64/ruby/2.5.0/open3.rb:264:in `read': stream closed in another thread (IOError)
#<Thread:0x000055d2e7e61c38@/usr/lib64/ruby/2.5.0/open3.rb:265 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /usr/lib64/ruby/2.5.0/open3.rb:265:in `block (2 levels) in capture3'
/usr/lib64/ruby/2.5.0/open3.rb:265:in `read': stream closed in another thread (IOError)
```

**Comment by MalloZup** [comment]
@arbulu89  closing as solved

**Comment by arbulu89** [comment]
@MalloZup This issue is not fixed. Having merged PRs is just a coincidence

**Comment by yeoldegrove** [comment]
This is not valid anymore as newer images use `registercloudguest` instead of `SUSEConnect`.
See https://github.com/SUSE/ha-sap-terraform-deployments/commit/ff5954abedc4e830467fe5034dfb5f300575e966 for reference.
