### ISSUE TITLE
GCP: user should be able to provide a zip to bucket for gcp

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#519]
Currenlty we have the folder where the extracted hana files should live. This has some limitations

https://github.com/SUSE/ha-sap-terraform-deployments/blob/74dca02c5b5e5c46a9b99ad71f3873c6f71b3e67/gcp/terraform.tfvars.example#L52

we should also research to give the user the ability to provide the path with the `zip` format files, instead of assuming the files are extracted there

**Comment by MalloZup** [comment]
@Simranpal did we achieved this? is there any doc avail?

**Comment by Simranpal** [comment]
@MalloZup yes, I added the feature  for all cloud, right now its in the terraform tfvars example files :

https://github.com/SUSE/ha-sap-terraform-deployments/blob/16b27530f03552448d3610b598a8602e8b04f747/gcp/terraform.tfvars.example#L78

**Comment by petersatsuse** [comment]
Maybe we need to clarify a bit the different ways SAP provides software for customers.

For example if you want the **installation** package of HANA you get a multi-archive rar file e.g. 51053381_part1.exe, 51053381_part2.rar ... which contains **all** deliverables like DB,Client,Studio,...

If you only want a ServicepackStack (similar to our Servicepacks) or Patchlevel, you can download a .sar file for the single tool you want to install, eg.  IMDB_SERVER20_024_10-80002031.SAR, which would be HANA2(0), SPS02(4), Patchlevel Version 10
