### ISSUE TITLE
DOC Add example for `zip/rar/exe/` media file

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#542]
Add support for zip,rar,exe,sar HANA media files. Q: there are no good examples for the usage.

@Simranpal cc @arbulu89

**Comment by arbulu89** [comment]
We have this in the `terraform.tfvars.example`.

```
# Or specify the path to the HANA installation archive file in either of SAR, RAR, ZIP, EXE formats, relative to the 'hana_inst_media' mounting point
# For multipart RAR archives, you only need to provide the first part EXE file name.
# If using hana sar archive, please also provide the compatible version of sapcar executable to extract the sar archive
# HANA installation archives be extracted to path specified at hana_extract_dir (optional, by default /sapmedia/HANA)
hana_archive_file = "IMDB_SERVER.SAR"
hana_sapcar_exe = "SAPCAR"
hana_extract_dir = "/sapmedia/HDBSERVER"
```

Is not enough?

**Comment by MalloZup** [comment]
this issue was reported by Peter schnagel. Ido think maybe we could add this reference to release note.

**Comment by petersatsuse** [comment]
regarding place of the SAP media: If a customer downloads e.g. the HANA files from SAP he will get this:
51053381_part1.exe
51053381_part2.rar
51053381_part3.rar
51053381_part4.rar

The examples show a) the fully unpacked directories b) something with a number - which is not clear how to use c) with a .sar archive and sapcar, and a extract dir - which does also not fit, as sapcar is normally not needed for HANA

**Comment by arbulu89** [comment]
@petersatsuse I will update the description, but remember that this is just an example. I'm afraid that we cannot cover all the use cases (and the `SAR` option with `SAPCAR` executable is one of them, even though you say that doesn't fit. Other users have requested this specifically).

**Comment by petersatsuse** [comment]
So how to use the above showed downloads, as this is what a customer downloads from SAP. With all other ways the customer had done something with downloaded files...or is using some former extracted parts

**Comment by petersatsuse** [comment]
1)
# Azure storage account path where HANA installation master is located
# hana_inst_master 

This mean to me is a path pointing to the *extracted* archive files 

2) 
# Or you can combine the `hana_inst_master with` `hana_platform_folder` variable.

This mean to me, i use the path above and in addition point to a directory

3) # Or specify the path to the HANA installation archive file in either of SAR, RAR, ZIP, EXE formats, relative to the 'hana_inst_media' mounting point.
# For multipart RAR archives, you only need to provide the first part EXE file name.

So i guess this would be the right option for my example, but at which variable i should provide the file name?

4) The next sentence make me unsure if 3) is right as there are 3 more variables to set.
# If using hana sar archive, please also provide the compatible version of sapcar executable to extract the sar archive
