### ISSUE TITLE
iscsi-formula not found error

### ISSUE THREAD

**Issue by gpandiya** [SUSE/ha-sap-terraform-deployments#543]
getting iscsi-formula not found error while executing sap-hana setup in AWS . 
Getting Package 'habootstrap-formula' not found error while executing sap-hana setup in AWS. 

Please provide detailed steps on execution to setup HA SAP-HANA on AWS.

**Comment by MalloZup** [comment]
@gpandiya can you provide more information about your envinronment?
which Image are you using and terraform.tfvars?

The formula are shipped in sles.

Thank you !

**Comment by risidoro** [comment]
Hi Dario,
I'm working with a customer, and their HANA deployment(azure) they will use an existing availability set.
the resource is in the file` \azure\modules\hana_node\main.tf` and the resource is this one:
```
resource "azurerm_availability_set" "hana-availability-set" {
  name                        = "avset-hana"
  location                    = var.az_region
  resource_group_name         = var.resource_group_name
  managed                     = "true"
  platform_fault_domain_count = 2

  tags = {
    workspace = terraform.workspace
  }
}
```
I'm already done a work around adding a variable to the hana_module: 

```
data "azurerm_availability_set" "hana-availability-set" {
  name                = var.hana-avset
  resource_group_name = var.resource_group_name
}
[ ... ]

resource "azurerm_virtual_machine" "hana" {
  [...]
  availability_set_id              = data.azurerm_availability_set.hana-availability-set.id
  [...]
```
Will be perfect is we can set the availability-set with the same approach like the vpc or the resource group

**Comment by gpandiya** [comment]
@MalloZup , using sap-sles-15-byos image. 

Few more errors

 ID: saphanabootstrap-formula
Function: pkg.installed
Result: False
Comment: Attempt 1: Returned a result of "False", with the following comment: "An error was encountered while installing package(s): Zypper command failure: 
Package 'saphanabootstrap-formula' not found."

ISCSI Setup

 module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):           ID: iscsid
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Function: service.running
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):       Result: False
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Comment: One or more requisite failed: cluster_node.ha.iscsi_initiator.iscsi_discovery

Thanks,

**Comment by gpandiya** [comment]
Also, please let me know how to check HANA setup post setup. There is no sapuser (sid user) created in hana suse linux systems. 

need details of sid-username for HANA. I could see only sapadm_password in pillar/hana/hana.sls file. Let me know if im missing anything. 

Thanks

**Comment by arbulu89** [comment]
@gpandiya As commented by @MalloZup we need more information from you.
Please, attach here the `terraform.tfvars` file you are using (comment your personal data obviously)

I would say that or you are not setting the `reg_code` or `ha_sap_deployment_repo` variables properly.

**Comment by gpandiya** [comment]
@MalloZup @arbulu89 

Attached terraform.tfvars file for your reference. Used this file for HANA Setup alone. 

[varsfile.txt](https://github.com/SUSE/ha-sap-terraform-deployments/files/5263203/varsfile.txt)

Thanks,

**Comment by arbulu89** [comment]
> @MalloZup @arbulu89
> 
> Attached terraform.tfvars file for your reference. Used this file for HANA Setup alone.
> 
> [varsfile.txt](https://github.com/SUSE/ha-sap-terraform-deployments/files/5263203/varsfile.txt)
> 
> Thanks,

Thanks @gpandiya ,
I have reviewed the file, and I see some changes are needed.

1. Comment the `hana_archive_file`, `hana_sapcar_exe` and `hana_extract_dir` variables. These variables are used to extract a HANA compressed file. The example was not really clear...
We have opened a PR to fix this. You can get more information in: https://github.com/SUSE/ha-sap-terraform-deployments/pull/546

2. I assume that you are using the current master branch version (this means release `v6`). To use this, use the following `ha_sap_deployment_repo`:
```
ha_sap_deployment_repo = "https://download.opensuse.org/repositories/network:ha-clustering:sap-deployments:v6"
```

3. I see that you are using BYOS images, but you are not setting the `reg_code` variable. This won't work. You have 2 options:
a. You get a valid SLES4SAP registration code, and you use it
b. You use PAYG images. For that, you will need to change the `hana_os_image` and `iscsi_os_image` (and they owner) with PAYG images (you can find the information in the AWS marketplace).

4. I recommend to set `pre_deployment = true` to avoid running some manual commands, and use the default pillar files.

The **piont 3** is the most critical. Without fixing this, everything else will fail.

Let me know if this helps you.

**Comment by gpandiya** [comment]
Thanks for your update and clarifying queries @arbulu89 , I have commented hana_archive_file, hana_sapcar_exe and hana_extract_dir variables and updated repo url. 
Updated hana_os_image and iscsi_os_image. using market place image SUSE Linux server 15 SP1 from aws. 

Error Images: 

![image](https://user-images.githubusercontent.com/71664429/94051012-9d3ba200-fdf4-11ea-896c-d1a5a63e2f35.png)

![image](https://user-images.githubusercontent.com/71664429/94051083-ae84ae80-fdf4-11ea-8762-1023320dfaa6.png)


Summary:
![image](https://user-images.githubusercontent.com/71664429/94050919-885f0e80-fdf4-11ea-9e3a-251631990714.png)

Logged into one of the node and tried below comments. Please update on now to verify HANA setup and s-user id (sid) to login as sap used and verify the setup. 

![image](https://user-images.githubusercontent.com/71664429/94051398-1d620780-fdf5-11ea-9a76-13107bf73d0f.png)

Thanks,

**Comment by arbulu89** [comment]
@gpandiya I cannot really say what's going on honestly without having the execution logs.
The error you pasted here means that the `iscsi` server is not working as expected. 
I see 2 possible solutions (as you are using AWS). 
1. Don't use SBD and use native fence mechanism. For that set `hana_cluster_sbd_enabled = false` in the terraform.tfvars file
2. I see that the `create_credentials_file` state failed. Do you have the your aws credentials file in the place you set in the terraform.tfvars file (`aws_credentials = "~/.aws/credentials"` in your case). Otherwise you can use `aws_access_key_id` and `aws_secret_access_key` options.

**Comment by gpandiya** [comment]
@arbulu89 Thanks for you update. I will the share the execution log file. 

yes, aws_credentials file is in place with correct credentials. If i set hana_cluster_sbd_enabled = false. getting below error. 

![image](https://user-images.githubusercontent.com/71664429/94124828-22659c00-fe73-11ea-8d5a-a8dfde2482c4.png)

Thanks,

**Comment by arbulu89** [comment]
@gpandiya The logs files are stored in `/var/log/salt-result.log`, `/var/log/salt-os-setup.log`, `/var/log/salt-predeployment.log` and `/var/log/salt-deployment.log`

**Comment by gpandiya** [comment]
@arbulu89 , add_cluster_profile worked now. 

issues only with below IDs, screenshots shared earlier. 

ID: iscsi_discovery
ID: iscsid
ID: wait_disk_id_available
ID: set_grains_sbd_disk_device

Thanks,

**Comment by arbulu89** [comment]
@gpandiya This is extremely strange.
Are you sure you are using `hana_cluster_sbd_enabled = false` ?
Setting this option should disable the `iscsi` server creation and the connection to it from the cluster nodes.
Is the `iscsi` server being created in your deployment?

Are you using the `latest` master branch (or `v6` tag version)?

**Comment by gpandiya** [comment]
@arbulu89 , Sorry my bad. 

Cloned the repo again and using v6 tag version. Attached my vars file (without using iscsi and sbd). correct me if I'm doing anything wrong. 

[aws-sap.txt](https://github.com/SUSE/ha-sap-terraform-deployments/files/5278320/aws-sap.txt)

commented this variable hana_cluster_sbd_enabled = false and by default it is false only. 

No iscsi server created in this setup. 
Os Setup and Pre-deployment succeeded with out any errors. 
Deployment is failing. 
Below are errors
Package 'SAPHanaSR' not found. 

![image](https://user-images.githubusercontent.com/71664429/94179338-fde0e280-feb9-11ea-9138-3072e0b79008.png)

![image](https://user-images.githubusercontent.com/71664429/94179365-089b7780-feba-11ea-807a-8f9dc4b9703c.png)


Thanks,

**Comment by arbulu89** [comment]
Hi @gpandiya ,
I still see that you are using `SLES` plain images. You need to use `SLES4SAP`. Try this in you `terraform.tfvars` file:

```
hana_os_image = "ami-01b462b77531c0987"
hana_os_owner = "679593333241"
# Additionally, you can increase the logging output with
#provisioning_log_level = "info"
```

This will deploy a SLES4SAP 15 SP1 version. To use other versions, you will need to find in the in the AWS marketplace.
`ami-0e3086eb56a7aaf20` would be SLES4SAP 15 SP2 for example.

**Important**. If you have something like the next error:
```
Error: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=dtiu2w0ef1urb9ucbu7pc60nv
	status code: 401, request id: 2f0706d9-2180-410f-84e5-86ab0419af55
```
This means that you are not subscribed to this particular image. Follow the instructions of the error and retry again

**Comment by MalloZup** [comment]
@gpandiya I'm adding needinfo please confirm if the last remarks fix for you so we can close. thx

**Comment by gpandiya** [comment]
@MalloZup Thanks for your updates. I'm working on the validations, will share the results once completed.

**Comment by gpandiya** [comment]
Hi @MalloZup , I have subscribed to market place image and tried to configure SAP hana setup. 

OS setup and pre-deployment completed without error. 

Deployment failing with below errors. I have SAPCAR and other installer files in S3 bucket pointed correctly. 

![image](https://user-images.githubusercontent.com/71664429/95012316-35d3ec80-0655-11eb-9c37-55fa242df08b.png)

**Comment by arbulu89** [comment]
Closing the issue as it comes to an configuration error. The `iscsi-formula` is available in the correct channels.
About the last error, it might be due some HANA version we have not tested, and creates some different issues in the commands we run.

If you want to follow, we could open other ticket, and try to reproduce the error with the same HANA version.
