### ISSUE TITLE
hard coded mount points break install and reboot

### ISSUE THREAD

**Issue by petersatsuse** [SUSE/ha-sap-terraform-deployments#549]
The mount point "/mnt" is in azure used by azure itself since our images switched to cloud-init instead of the azure own waagent.

So in azure there is now a ephemeral disk is mounted on '/mnt'. As we create additional mount points below /mnt like for mounting a NFS share, such mount points will be not exist anymore after a reboot.

As this hard coded mount point need to be changed in several files at once it would be much better to have that as a variable which is used in the relevant files. So if it is conflicting like in azure, it could be changed on one single place instead in several places in various files.

**Comment by arbulu89** [comment]
Hi @petersatsuse . You mean that we need to change the `drbd` mounting point specifically, right?
As we use `/mnt/sapdata`.
