### ISSUE TITLE
Enhancement Using .SAR files with monitoring.

### ISSUE THREAD

**Issue by stephenmogg** [SUSE/ha-sap-terraform-deployments#558]
As discussed before, using .SAR files is very clean (in terms of how to present the sap media).  (just two files to upload which can be downloaded directly from SAP Download site).

This is partially implemented if we are just installing a SAP HANA Cluster and works perfectly.

However, if monitoring is required then the HANA Client is also needed.  This is not part of the HANA DB SAR file.

The request:
Could we have a 3rd '.SAR' variable (and some logic) for the HDB Client?  I can't get to the SAP download site, but imagine it's just another single executable or even a SAR file.

Thanks

**Comment by stephenmogg** [comment]
or .. just be able to present the 4 multi-part .rar files.
I appreciate this does not provide any more functionality (and likely slows down the deployment as it is unpacked) but it does make it easier to present the SAP media.

**Comment by MalloZup** [comment]
@stephenmogg  hi ok I see. where do you have discussed before?
I think you are referring to `hanadb` exporter and the way it get the `python` driver database installation. 

Ok that could make sense I think we need to research and see how to provide this feature in a generic way.

**Comment by arbulu89** [comment]
> or .. just be able to present the 4 multi-part .rar files.
> I appreciate this does not provide any more functionality (and likely slows down the deployment as it is unpacked) but it does make it easier to present the SAP media.

This option is already available. You can use something like `hana_archive_file = "51053381_part1.exe`.

In the other hand, the option to use an additional `SAR` file for the HANA client is not implemented. We will add this feature in our backlog

**Comment by stephenmogg** [comment]
Thanks.   I might open another issue for this, but using the 4 part exe/rar works fine for a HANA HA cluster.....
.. until you want a monitoring server too.  Then it fails (during extraction?), I'll try and find the time to grab some logs.

**Comment by arbulu89** [comment]
> Thanks. I might open another issue for this, but using the 4 part exe/rar works fine for a HANA HA cluster.....
> .. until you want a monitoring server too. Then it fails (during extraction?), I'll try and find the time to grab some logs.

I have tested this, and it worked fine for me. It created the cluster and set the monitoring client. Maybe I have some fixes in the `develop` branch.

**Comment by arbulu89** [comment]
Closing. Implemented in https://github.com/SUSE/saphanabootstrap-formula/pull/111
