### ISSUE TITLE
Enhancement - Keeping the fileshare with HANA clean (by just uploading SAP car and SAR file)

### ISSUE THREAD

**Issue by stephenmogg** [SUSE/ha-sap-terraform-deployments#56]
Consider just having SAPCAR.EXE (Linux edition) and HANA SAR file in the upload.
Then get the automation to download and extract locally on VM from cloud storage.

**Pros.**
Keeps the Fileshare / S3 bucket nice and clean with just two files in (or perhaps can use BLOB storage).
Easy to upload (initially)
Easy to update with new/multiple versions.  (ie. V1 or V2 etc)

**Cons.**
Inefficient - automation will have to extract each time - so will add to build time.

**Comment by diegoakechi** [comment]
One more Pro here is that it sounds more friendly to users as the compressed file is how he faces the SAP download center and need to learn how to extract that can be tedious and repetitive.

**Comment by ricardobranco777** [comment]
This is how it's currently done in the GCP deployment.  With such a number of cores and huge memory, the decompression is not that time-consuming.  It may be even more faster if the decompression utility is parallelized (like `pigz` for `gzip`, for example).  I have to investigate whether `unrar` is parallelized or not, and search for a comparable tool if not.

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue older then 130days. Please update the issue or close it

**Comment by Simranpal** [comment]
We added support for sar file extraction in the sap formulas:
https://github.com/SUSE/saphanabootstrap-formula/pull/76
https://github.com/SUSE/sapnwbootstrap-formula/pull/41

With the terraform project, relevant changes are added here:
https://github.com/SUSE/ha-sap-terraform-deployments/pull/417
https://github.com/SUSE/ha-sap-terraform-deployments/pull/414
