### ISSUE TITLE
unify ssh key variable from 2 to one unique variable

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#589]
Right now we ask the user 2 variables for ssh_key (private and public)
https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/azure/terraform.tfvars.example#L89-L93

We don't need to ask for this.

We can just ask for the `private` key and for the public we use the private with postifx `.pub` automatically appended.

So we spare 1 variable and errors.

**Comment by stefanotorresi** [comment]
As discussed in RC I don't think this is a good idea. If we want to simplify credentials management then we should rethink it all.
