### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stephenmogg** [SUSE/ha-sap-terraform-deployments#59]
It might be worth commenting in the 'How to use section' that the image.tf file needs to be removed if using public images.  

(There is a section on renaming the virtualmachines.tf-publicimg, but not the fact that image.tf is not needed either).

If future versions will be designed for 'public images first' then you can ignore this.

**Comment by arbulu89** [comment]
Thank you for the comment @stephenmogg 
We are working in a new PR to adapt some features in the Azure deployment, and we will work in this README file there.
Thanks for the feedback
