### ISSUE TITLE
AWS NW deployment failure

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#599]
Hi, 

I am deploying NW HA cluster operating on AWS to certify NW 7.5 on SLE12. I am using the SAP Automation v6. I am using the same AWS bucket that I used for the NW certification on SLE15, so the software hierarchy should be OK. however,  the deployment was failed using the previously created AWS S3 bucket and even after updating the `SWPM`, `SAP IGS` and `SAP Host Agent` to the most recent SAP versions.

The deployment failed with the following error messages:
```
module.hana_node.module.hana_provision.null_resource.provision[1]: Creation complete after 20m5s [id=3714711867284409347]

Warning: Value for undeclared variable
  on terraform.tfvars line 83:
  83: hana_disk_device = "/dev/xvdd"
The root module does not declare a variable named "hana_disk_device". To use
this value, add a "variable" block to the configuration.
Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.

Error: error executing "/tmp/terraform_1319189064.sh": Process exited with status 1
Error: error executing "/tmp/terraform_1377044729.sh": Process exited with status 1
Error: error executing "/tmp/terraform_1493255618.sh": Process exited with status 1
Error: error executing "/tmp/terraform_1390571780.sh": Process exited with status 1
```

Troubleshooting steps:
-------------------------------------
1. Deploying SAP HANA HA cluster without NW. It worked fine.
2. Checking the connectivity between the NetWeaver nodes and the AWS S3 buckets. it worked fine.
3. I checked the OS version and I ensured it is SLES 12 SP4 for SAP Applications. 

Notes:
------
1. `/var/log/provisioning.log` file does not exist on `netweaver01` or `netweaver02` nodes.
2. `crm_mon` command executed on the NetWeaver nodes shows that  ASCS and ERS are working!
3. When I checked the ACSC and ERS status, I found the following:
```
netweaver01:ha1adm 7> sapcontrol -nr 00 -function GetProcessList

18.11.2020 12:55:24
GetProcessList
OK
name, description, dispstatus, textstatus, starttime, elapsedtime, pid
msg_server, MessageServer, GREEN, Running, 2020 11 18 12:11:15, 0:44:09, 26052
enserver, EnqueueServer, GREEN, Running, 2020 11 18 12:11:16, 0:44:08, 26053
```
```
netweaver02:ha1adm 3> sapcontrol -nr 10 -function GetProcessList

18.11.2020 12:56:20
GetProcessList
OK
name, description, dispstatus, textstatus, starttime, elapsedtime, pid
enrepserver, EnqueueReplicator, GREEN, Running, 2020 11 18 12:13:37, 0:42:43, 27669
```

I am attaching the following files:
1. `terraform.tfvars` file
2. NetWeaver and HANA pillar files.
3. `/var/log/salt-deployment.log` log file for each Netweaver node are attached after a quick check against errors. Also, I attached also a truncated version focusing on the `ERROR` messages only. 
4. Cluster monitoring result.

**Comment by arbulu89** [comment]
Hi @ab-mohamed ,
This issue was fixed after https://github.com/SUSE/sapnwbootstrap-formula/pull/68
Right?
Thank you

**Comment by ab-mohamed** [comment]
@arbulu89. Yes. Thanks for your help. This is can be closed now.
