### ISSUE TITLE
Reorganize the terraform files into modules

### ISSUE THREAD

**Issue by diegoakechi** [SUSE/ha-sap-terraform-deployments#6]
Terraform provides the capability of creating modules to better code organization and to create reusable components. [See: Creating Modules](https://www.terraform.io/docs/modules/create.html).

Moving some of the components to modules could help to create more complexes deployments, like Scale-out, HANA with multi system replication, reusing the already existing code.

**Comment by MalloZup** [comment]
@diegoakechi  afaik this could be closed

**Comment by MalloZup** [comment]
## info:

this issue concern mostly the cloud providers to be modularized.

**Comment by MalloZup** [comment]
closing in favor of more specific issue! thx https://github.com/SUSE/ha-sap-terraform-deployments/issues/107
