### ISSUE TITLE
Error at the end of the process - cp pillar_examples/automatic/hana/* pillar/hana/;

### ISSUE THREAD

**Issue by picoroma** [SUSE/ha-sap-terraform-deployments#604]
I tried to deploy a simple HANA Cluster with 2 nodes using the script.

I choose to NOT deploy SAP netweaver nor the S4 - but only the HANA cluster (simplest scenario).
The deploy seems to be OK and everything seems to work fine.
But at the very end of the process (the last output I have) – in the terraform console I have this final error – before the script end:
 
![Screenshot_91](https://user-images.githubusercontent.com/23618664/99944549-59710480-2d73-11eb-9797-ec1f599ca013.jpg)

 
I’m quite sure that everything finished well at the server side…
I can See both SAP HANA Node on HANA Studio and also the SUSE cluster seems OK:
![Screenshot_92](https://user-images.githubusercontent.com/23618664/99944573-655cc680-2d73-11eb-8424-53784d93c03e.jpg)

 What can be the problem and how to avoid it ?
THX

**Comment by arbulu89** [comment]
@picoroma ,
How did you reproduce this error?
Do you have `pre_deployment` variable set to true in your `terraform.tfvars` file?

I have not tested that in Windows environments. Most probably there is something wrong.
Anyway, as you stated, this won't affect the deployed cluster in any case, it will be just an annoying message hehe

We will have a look.

**Comment by picoroma** [comment]
Hi!
YES, I think I have the pre_deployment variable set to true.
Do I neet to set it to false ?
P.

**Comment by arbulu89** [comment]
> Hi!
> YES, I think I have the pre_deployment variable set to true.
> Do I neet to set it to false ?
> P.

Setting the `pre_deployment` to `true` will enable the usage of this command (among other things), so to get rid off this error, set it to `false`

**Comment by yeoldegrove** [comment]
If there is an easy reproducer, please reopen.
