### ISSUE TITLE
Confusing usage of names/variables in /libvirt/terraform.tfvars.example

### ISSUE THREAD

**Issue by pirat013** [SUSE/ha-sap-terraform-deployments#606]
At line 8 the is a question for a range: -> iprange = "192.168.XXX.Y/24" but it looks like a subnet and not a range. For me a range would be something like this: iprange = "192.168.XXX.Y+128/24 - 192.168.XXX.Y+254/24"

At line 36 the HANA IP's are defined: #hana_ips         = ["192.168.XXX.Y", "192.168.XXX.Y+1"] . This looks a bit strange, if I define a "iprange = 192.168.10.0/24"  this would result in this two IP's: 192.168.10.0/24 & 192.168.10.1/24
In the meantime I'm aware of the fact the the HANA IP's will have a start IP of 10 in the main.tf file. If you are not aware of that and compared the HANA IP's and the iSCSI IP's it a bit confusing (#iscsi_srv_ip = "192.168.XXX.Y+6").

**Comment by arbulu89** [comment]
Hi @pirat013 ,

We created a doc to try to clarify the IP auto generation (and the examples are based on that):
https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/doc/ip_autogeneration.md

Coming to your comments. I don't know why you say `192.168.XXX.Y/24` doesn't look like as a IP range. This is how ranges are defined using a mask. It just means that it includes all the IP addresses between `192.168.XXX.1` and `192.162.XXX.255`.

About the specific addresses, those are just examples... Don't take them as granted. We should just be aware that `192.168.XXX.0` wouldn't be allowed, as it is a reserved address. But this I guess is just networking basics...

We always recommend to use the auto generated addresses unless you are totally sure how you want to configure the network layer. We don't do (and we cannot) any validation with the addresses. They must be correct. If you don't initialize any of the addresses, there must be some logic. If you set the addresses, they will set as you put them.

**Comment by arbulu89** [comment]
Closing the ticket as I don't see how we could address the asked question.
We can reopen if needed in the future.
