### ISSUE TITLE
Netweaver NFS share unavailable

### ISSUE THREAD

**Issue by Simranpal** [SUSE/ha-sap-terraform-deployments#613]
In our  jenkins CI, the Netweaver deployment fails. This issue happens speriodically but quite frequently.

The salt state to wait for Netweaver NFS availability timeouts.  The NFS share is provided by drbd in the CI.
The issue may happen due to a DRBD issue, however no errors reported by dbrd nodes. The issue happens when the drbd provisioning took longer and it may be due to shorter wait time for NFS server availability.

Below is the salt provision logs:

```
07:14:49 module.netweaver_node.module.netweaver_provision.null_resource.provision[1] (remote-exec): ID: wait_until_nfs_is_ready
07:14:49 module.netweaver_node.module.netweaver_provision.null_resource.provision[1] (remote-exec): Function: cmd.run
07:14:49 module.netweaver_node.module.netweaver_provision.null_resource.provision[1] (remote-exec): Name: until nc -zvw5 192.168.15.22 2049;do sleep 30;done
07:14:49 module.netweaver_node.module.netweaver_provision.null_resource.provision[1] (remote-exec): Result: False
07:14:49 module.netweaver_node.module.netweaver_provision.null_resource.provision[1] (remote-exec): Comment: Command "until nc -zvw5 192.168.15.22 2049;do sleep 30;done" run
07:14:49 module.netweaver_node.module.netweaver_provision.null_resource.provision[1] (remote-exec): Started: 14:54:34.448381
07:14:49 module.netweaver_node.module.netweaver_provision.null_resource.provision[1] (remote-exec): Duration: 1200009.129 ms
```

example in full log: https://ci.suse.de/job/sles-sap-terraform-deployment-nw/15/PROVIDER=libvirt,SLES4SAP=sles15sp1,label_exp=sles-sap/consoleFull

**Comment by arbulu89** [comment]
@Simranpal I'm closing this ticket. This error is caused for lack of resources in our infrastructure. As the CI is running 3 jobs in parallel, that create around 20 machines, the performance just goes down, and some machines take a lot of time finishing some operations, that finally causes the error.
Running the jobs in parallel fixes the issue
