### ISSUE TITLE
Document how to use the `hana_data_disks_configuration` variable

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#622]
This variable defines how to configure the Disks setup for HANA in Azure.

Here a comment explaining how it works: https://github.com/SUSE/ha-sap-terraform-deployments/pull/620#issuecomment-769181592

The creation of `PV`, `VG` and `LVM` is based on this dictionary, but it is not explained how to change it.
Initially, it wasn't meant for the user to change as it is quite complex, and we created some examples that they can puts without really understanding the logic behind the variable.

In any case, it would be valuable to document it

**Comment by petersatsuse** [comment]
there are some (highlevel) parts in the docu for the Azure ARM Templates Project
https://github.com/SUSE/azure-resource-manager-sap-solution-templates/blob/master/docu/AzureSolutionTemplates_Documentation.adoc
