### ISSUE TITLE
SAP HANA HA Cluster on GCP - Corosync Configurations

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#624]
Hi, 

The following parameters and notes are based on the https://cloud.google.com/solutions/sap/docs/sap-hana-ha-dm-deployment-sles GCP guide. 

I compared the Corosync configurations set by the google team in the `/etc/corosync.conf` file and the ones we set in the GCP deployment here. 

We need to update the values of the following parameters:

Corosync Configuration Parameter  | Current value | Google Set Value 
----------------------------------------------- | ------------------ | ------------------------
`secauth`  | `on`  | `off`
 `token` | `5000` | `20000`
 `consensus` |  `6000` | `24000`

Also, I have some notes/questions to share here:

- Google set `/etc/corosync.conf` file uses the `bindnetaddr` parameter which I believe it is not mandatory as HA configurations on GCP uses the Unicast way only `udpu`. Unless you have other opinions, I would advise to remove it from the Google set corosync configurations. 
- Google set `/etc/corosync.conf` file uses the DNS hostname value for the `ring0_addr`. Would it be better to use the IP address as stated in the `corosync.conf` man page regarding `ringX_addr` option?   
```
# man corosync.conf
[...]
       ringX_addr
              This specifies IP address of one of the nodes. X is ring number.
[...]
```

**Comment by ab-mohamed** [comment]
Here is the `/etc/corosync.conf` file from HANA node created using ` https://cloud.google.com/solutions/sap/docs/sap-hana-ha-dm-deployment-sles` guide:
```
    totem {
      version: 2
      secauth: off
      crypto_hash: sha1
      crypto_cipher: aes256
      cluster_name:	hacluster
      clear_node_high_bit: yes
      token: 20000
      token_retransmits_before_loss_const: 10
      join: 60
      consensus: 24000
      max_messages:	20
      transport: udpu
      interface {
        ringnumber:	0
        bindnetaddr: 192.168.0.11
        mcastport: 5405
        ttl: 1
      }
    }
    logging {
      fileline:	off
      to_stderr: no
      to_logfile: no
      logfile: /var/log/cluster/corosync.log
      to_syslog: yes
      debug: off
      timestamp: on
      logger_subsys {
        subsys: QUORUM
        debug: off
      }
    }
    nodelist {
      node {
        ring0_addr: hana01
        nodeid: 1
      }
      node {
        ring0_addr: hana02
        nodeid: 2
      }
    }
    quorum {
      provider: corosync_votequorum
      expected_votes: 2
      two_node: 1
    }
```

**Comment by ab-mohamed** [comment]
and here the  `/etc/corosync.conf` file from HANA node created using SUSE automation project:
```
# Please read the corosync.conf.5 manual page
totem {
	version: 2
	secauth: on
	crypto_hash: sha1
	crypto_cipher: aes256
	cluster_name: hana_cluster
	clear_node_high_bit: yes
	token: 5000
	token_retransmits_before_loss_const: 10
	join: 60
	consensus: 6000
	max_messages: 20
	interface {
		ringnumber: 0
		mcastport: 5405
		ttl: 1
	}

	transport: udpu
}

logging {
	fileline: off
	to_stderr: no
	to_logfile: no
	logfile: /var/log/cluster/corosync.log
	to_syslog: yes
	debug: off
	timestamp: on
	logger_subsys {
		subsys: QUORUM
		debug: off
	}

}

nodelist {
	node {
		ring0_addr: 192.168.1.11
		nodeid: 1
	}

	node {
		ring0_addr: 192.168.1.12
		nodeid: 2
	}

}

quorum {

	# Enable and configure quorum subsystem (default: off)
	# see also corosync.conf.5 and votequorum.5
	provider: corosync_votequorum
	expected_votes: 2
	two_node: 1
}
```

**Comment by ab-mohamed** [comment]
So, based on my conversation with @gao-yan: As long as `nodelist` is configured with `ringX_addr`, `bindnetaddr` is not required, no matter if it's `unicast` or `mcast`.

**Comment by arbulu89** [comment]
Fixed in: https://github.com/SUSE/ha-sap-terraform-deployments/pull/639
