### ISSUE TITLE
GCP Load Balancer Implementation 

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#625]
Hi,

Google team has introduced the usage of the load balancer as a cloud-native component that provides the floating IP function. It will be the primarily used option and the `gcp-vpc-move-route` resource agent will be used as the second option to cover some VPC network implementation.

The load balancer is implemented in the pacemaker cluster configurations using `anything` and `IPaddr2` resource agents. following configurations were captured from a working environment was created based on the [Automated SAP HANA HA deployment on SLES with load-balancer VIP implementation](https://cloud.google.com/solutions/sap/docs/sap-hana-ha-dm-deployment-sles) guide:
```
primitive rsc_vip_hc-primary anything \
        params binfile="/usr/bin/socat" \
       cmdline_options="-U TCP-LISTEN:60005,backlog=10,fork,reuseaddr /dev/null" \
        op monitor timeout=20s interval=10 \
        op_params depth=0
```
```
primitive rsc_vip_int-primary IPaddr2 \
        params ip=192.168.0.100 cidr_netmask=32 nic=eth0 \
        op monitor interval=10s
```
 
We need to add the load balancer function and configurations to the GCP deployments 

Best regards,
Ab

**Comment by arbulu89** [comment]
Implemented in https://github.com/SUSE/saphanabootstrap-formula/pull/121 and https://github.com/SUSE/ha-sap-terraform-deployments/pull/659
