### ISSUE TITLE
SAP HANA HA Cluster on GCP - Pacemaker Configurations Notes

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#626]
Hi, 

Following are my pacemaker notes and questions after deploying SAP HANA HA cluster on GCP using `version 6` -> master branch:

1. Even if I did not enable `hana_active_active` Terraform variable, The pacemaker configurations show that the HANA Operation Mode is `logreplay_readaccess`
Here is the pacemaker configurations part:
```
node 1: default-hana01 \
	attributes lpa_prd_lpt=1612799151 hana_prd_vhost=default-hana01 hana_prd_site=NUE hana_prd_op_mode=logreplay_readaccess hana_prd_srmode=sync hana_prd_remoteHost=default-hana02
node 2: default-hana02 \
	attributes lpa_prd_lpt=30 hana_prd_op_mode=logreplay_readaccess hana_prd_vhost=default-hana02 hana_prd_remoteHost=default-hana01 hana_prd_site=FRA hana_prd_srmode=sync
```
And here is the terraform variable configuration:
```
$ grep -B1 hana_active_active terraform.tfvars 
# Enable Active/Active HANA setup (read-only access in the secondary instance)
#hana_active_active = true
```
```
$ grep -A4 hana_active_active variables.tf 
variable "hana_active_active" {
  description = "Enable an Active/Active HANA system replication setup"
  type        = bool
  default     = false
}
```

2. `SAPHana` resource agent parameters `PREFER_SITE_TAKEOVER` and `AUTOMATED_REGISTER` values should be updated as follows to comply with [SAP HANA System Replication Scale-Up - Performance-Optimized Scenario](https://documentation.suse.com/en-us/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/) guide:

Current Configurations | Desired Configurations
------------------------------ | -------------------------------
`PREFER_SITE_TAKEOVER=True` | `PREFER_SITE_TAKEOVER="true"`
`AUTOMATED_REGISTER=False` | `AUTOMATED_REGISTER="false"`

**Comment by arbulu89** [comment]
Thanks @ab-mohamed 
My comments:
1. You are right, it looks like there is something wrong there. I will need to investigate further
2. In the resource agents configuration `True` or `"true"` are the same. After configuring from template, the quotes are removed. Here the code to check if a value is `true` for example: https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/ocf-shellfuncs.in#L102

**Comment by ab-mohamed** [comment]
Thanks, @arbulu89,

1. I will be testing the new branch once it is ready and I will keep you updated. 
2. Thanks for the hint. so, it would not make a difference if set the value in the "" or not?

**Comment by arbulu89** [comment]
@ab-mohamed Having quotes or not is indifferent yest

Fixed in: https://github.com/SUSE/ha-sap-terraform-deployments/pull/638
