### ISSUE TITLE
[question] terraform - plans to support a more recent version of terraform?

### ISSUE THREAD

**Issue by roseswe** [SUSE/ha-sap-terraform-deployments#641]
Are there plans or is it supported in this project to use a more recent version of terraform that 0.12.6?

E.g. 

$ terraform -version
Terraform v0.14.7

_or_
Information for package terraform:

Repository     : SLE-Module-Public-Cloud15-SP2-Updates
Name           : terraform
Version        : 0.13.4-6.3.1
Arch           : x86_64

**Comment by arbulu89** [comment]
Hi @roseswe ,
Actually the project is based on `terraform v0.13.4`.
We forgot to update the README.md.
I will do the change
Thanks!

**Comment by arbulu89** [comment]
Hi @roseswe ,
I have checked and this has been already fixed for `develop` branch.
As we don't expect to have more hotfix releases by now in `master/6.0.x` branches, it will come the next time `develop` is merged to `master`.
https://github.com/SUSE/ha-sap-terraform-deployments/commit/3d7e24693ae165a3508f503b5d85b589945316d8

Can we close this ticket or do you have more questions about this?

**Comment by roseswe** [comment]
thanks for feedback!
