### ISSUE TITLE
Prevent GCP environment to be exposed to the internet

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#644]
Hi, 

I assume that my request has been implemented in the Azure network implementation.

The current network implementation for the GCP HANA, NetWeaver, and DRBD/NFS HA clusters and Monitoring Servers provides access to them over the internet. 

Could you please adjust the current network implementation to:
1.  Deploy the environment instances in a protected private network(s).
2.  Create a bastion host that is exposed to the internet and used to access the whole environment?

Best regards,
Ab

**Comment by arbulu89** [comment]
Hi @ab-mohamed ,
I would need some help here. Do you have some architectural details document where I can base my implementation?
I need to know the network setting (used vpc, network, firewall rules, etc) for a environment based in a bastion host.

**Comment by arbulu89** [comment]
Adding link with information:
https://cloud.google.com/solutions/sap/docs/sap-hana-ha-dm-deployment-sles

**Comment by arbulu89** [comment]
Implemented in: https://github.com/SUSE/ha-sap-terraform-deployments/pull/654
