### ISSUE TITLE
v7: terraform plan asks for NW password even if NW is not enabled in tfvar file

### ISSUE THREAD

**Issue by petersatsuse** [SUSE/ha-sap-terraform-deployments#649]
v7: terraform plan asks for NW password even if NW is not enabled in tfvar file

**Comment by arbulu89** [comment]
Yes, this is a needed limitation. We don't want to put a default password, because the users wouldn't change it

**Comment by petersatsuse** [comment]
ok, understand, but its from the usage point of view not nice. 
I want to deploy a HANA DB and get asked about the Netweaver password.

**Comment by arbulu89** [comment]
@stefanotorresi @MalloZup 
What do you think of this? I didn't want to put default passwords because it can be a security hole but it creates this bad behaviour. It is a pity that terraform doesn't have conditional variables usage...

**Comment by stefanotorresi** [comment]
Yeah, this is a tricky one. The only thing I can think of right now is to introduce an additional layer to configure the terraform variables via CLI, like you did demonstrate in the past, but it's not an trivial thing to do.

**Comment by petersatsuse** [comment]
what if the default is set to "null" 

It looks like newer version have some improvements here
https://www.hashicorp.com/blog/terraform-0-12-conditional-operator-improvements

**Comment by ab-mohamed** [comment]
Btw, I confirm the same issue when I deploy HANA HA cluster on GCP.

**Comment by arbulu89** [comment]
Hey @ab-mohamed and @petersatsuse ,
I have implemented a solution to avoid this behaviour. It is not really a terraform way, because we are converting the code more and more an imperative style, but well, it is what it is. Terraform is limited in many ways.

**Comment by arbulu89** [comment]
Fixed in: https://github.com/SUSE/ha-sap-terraform-deployments/pull/659
