### ISSUE TITLE
Configure Chrony instead of NTP for SLE-15.

### ISSUE THREAD

**Issue by diegoakechi** [SUSE/ha-sap-terraform-deployments#65]
NTP was replaced by Chrony on SLE-15 and higher code streams, so the deployments should be adjusted to configure Chrony instead of NTP.

NTP is still available on the sle-module-legacy and it is supported, but as the legacy module is not supported for the entire product lifecycle, this switch should be done ASAP.

**Comment by alvarocarvajald** [comment]
Isn't `chrony` also managed via the `yast2-ntp-client` module?

**Comment by arbulu89** [comment]
> Isn't `chrony` also managed via the `yast2-ntp-client` module?

Yes, it configures chrony as well.
https://www.suse.com/documentation/sles-15/book_sle_admin/data/cha_ntp.html

The manual configuration is almost exactly the same than ntp. I'm preparing some changes in https://github.com/SUSE/habootstrap-formula to adapt the code to use chrony.

**Comment by diegoakechi** [comment]
The changes were included on the habootstrap-formula, and will be available on the RPM package as soon as it gets built. So, I am marking this issue as solved.
