### ISSUE TITLE
v7: if monitoring is enabled, the deployments fails, because of loki can not be installed

### ISSUE THREAD

**Issue by petersatsuse** [SUSE/ha-sap-terraform-deployments#650]
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): ----------
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):           ID: node_exporter_service
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Function: service.running
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):         Name: prometheus-node_exporter
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):       Result: True
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Comment: Service prometheus-node_exporter has been enabled, and is running
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Started: 19:24:39.206494
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Duration: 337.587 ms
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Changes:
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):               ----------
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):               prometheus-node_exporter:
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):                   True
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): ----------
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):           ID: loki
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Function: pkg.installed
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):       Result: False
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Comment: Attempt 1: Returned a result of "False", with the following comment: "An error was encountered while installing package(s): Zypper command failure: Running scope as unit: run-rcbcc1fcc48d44225b7659be9e3c6638e.scope"
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):               Attempt 2: Returned a result of "False", with the following comment: "An error was encountered while installing package(s): Zypper command failure: Running scope as unit: run-r29b9465033134b9f97324c1ad0553c70.scope"
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):               An error was encountered while installing package(s): Zypper command failure: Running scope as unit: run-r3d8d2326ff5c459e88352bc0f8918824.scope
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Started: 19:24:39.548363
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Duration: 34847.748999999996 ms
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Changes:
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): ----------
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):           ID: promtail_config
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Function: file.managed
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):         Name: /etc/loki/promtail.yaml
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):       Result: False
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Comment: Parent directory not present
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Started: 19:25:14.422540
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Duration: 7.662 ms
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Changes:
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): ----------
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):           ID: loki_systemd_journal_member
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Function: group.present
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):         Name: systemd-journal
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):       Result: False
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Comment: One or more requisite failed: cluster_node.monitoring.loki
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Started: 19:25:14.433017
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Duration: 0.004 ms
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Changes:
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): ----------
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):           ID: promtail_service
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Function: service.running
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):         Name: promtail
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):       Result: False
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Comment: One or more requisite failed: cluster_node.monitoring.loki, cluster_node.monitoring.promtail_config, cluster_node.monitoring.loki_systemd_journal_member
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Started: 19:25:14.434474
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Duration: 0.003 ms
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Changes:
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): ----------

**Comment by arbulu89** [comment]
Hi @petersatsuse ,
Did you put the `ha_sap_deployment_repo` as commented in the release information: https://github.com/SUSE/ha-sap-terraform-deployments/releases/tag/7.0.0?

**Comment by petersatsuse** [comment]
yes, i use the v7 version - which got  the above error, i tried to switch to the -devel packages, and this was working. So something
is broken in the v7 packages.

**Comment by arbulu89** [comment]
@petersatsuse Which SLE version did you use?
There are some issues building the image in SLE12, most probably it won't go there. 
A really recent change was added. I will need to filter loki installation on SLE12

**Comment by petersatsuse** [comment]
the default from the project - no change, so 15sp2

**Comment by arbulu89** [comment]
That's strange. `devel` and `v7` are exactly the same. I will try to reproduce the error

**Comment by arbulu89** [comment]
Here the fix for SLE12: https://github.com/SUSE/ha-sap-terraform-deployments/pull/653
Besides that, after testing I have not found any relevant issue.
Closing the ticket
