### ISSUE TITLE
v7: GCP deployment notes

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#656]
Hi, 

The first part of my notes here will be dedicated to the SAP HANA HA cluster deployment part:

**`terraform.tfvars` file:**

1. `deployment_name "mydeployment"` -> There is a missed `=` sign
1. `pre_deployment = true` ->  It should be commented out as it disabled by default.
2. `hana_data_disk_type` -> Adding a short comment states that the default value would be a nice reading experience enhancement.  The same also applies to `hana_data_disk_size`, `hana_backup_disk_type` and `hana_backup_disk_size`. 
4. `monitoring_os_image = suse-byos-cloud/sles-15-sp2-sap-byos` -> the parameter value needs to be set inside `""`.

**Comment by ab-mohamed** [comment]
This part will be dedicated to the NW HA deployment:

**`terraform.tfvars` file:**
1. `#drbd_os_image = suse-byos-cloud/sles-15-sp2-sap-byos` -> the value needs to be set within `""`.
2. `#netweaver_machine_type = n1-standard-4` -> The default value is `n1-highmem-8` not `n1-standard-4`. 
3. `#netweaver_machine_type = n1-standard-4`  -> the value needs to be set within `""`.
4. `#netweaver_os_image = suse-byos-cloud/sles-15-sp2-sap-byos` -> the value needs to be set within `""`

**Comment by ab-mohamed** [comment]
@arbulu89 FYI.

**Comment by arbulu89** [comment]
@ab-mohamed Most of the things fixed in https://github.com/SUSE/ha-sap-terraform-deployments/pull/675
I don't get the `hana_data_disk_size` point. They already have a default value defined and for default values you can always go to the `variables.tf` file as documented in the REAMDE file

**Comment by arbulu89** [comment]
Fixed in: https://github.com/SUSE/ha-sap-terraform-deployments/pull/675
