### ISSUE TITLE
Enhancement: required package list for the project

### ISSUE THREAD

**Issue by nick-wang** [SUSE/ha-sap-terraform-deployments#671]
The terraform project is not RPM based. However, it did required the packages set with the minimized version. We only mark this in release note after bumped up the tags. It is better to show this in projects as well.

Two options can be used for this:
1) Implemented in salt code, like https://github.com/SUSE/ha-sap-terraform-deployments/commit/dbb6fcdd60d1c3f21b7cc23581f0c5578f630708
However, the side effect is user/develper may don't know this file and forget to update when needed.
2) Add a `requirements.txt` in top level, without force install/check. Further more, could implement a script after installation to check the environment with the `requirements.txt`

**Comment by nick-wang** [comment]
Some ideas for the solution:
Create a plain text listed packages/versions like `requirements.txt` in top level.

Then three methods to use this file:
1. Compare the packages after predeploy stage
Mark ERROR in logs if installed packages too old, WARN if list packages not installed. 
In this case, doesn't need to check the node role of var flag with corresponding packages. (eg. drbd-formula not in hana node)
No matter the result, only record it in log file. So that user still can add repo/install new versions during deploy stage.

2. WIthout calling the package check after predeploy stage. Only implement a checker to get logs and environment when needed to ease the debug. 
In this case, we can add more things into the checker than just check package versions.

3. Find a way to get the version from the requirements.txt into all salt state of pkg.installed in salt of ha-sap-terraform project

**Comment by nick-wang** [comment]
After discussed with @arbulu89 we agree to use solution like this:
+ Create a `requirements.txt` to list all the required packages with `exactly` version needed
+ If `ha_sap_deployment_repo` not provided in `terraform.tfvars`. Install the exactly version packages based on the file before `predeply` stage.
   Just install the latest version during `prodeploy` stage if `ha_sap_deployment_repo` provided.

Notes:
+ Need to update `requirements.txt` when required packages changed, before SCC released. Use `ha_sap_deployment_repo` with corresponding OBS project `network:ha-clustering:sap-deployments:xxx` is needed. Version specifc.
+ Need to mentioned the usage/change of `requirements.txt` to doc file for all contributors.

**Comment by arbulu89** [comment]
Implemented at: https://github.com/SUSE/ha-sap-terraform-deployments/pull/678
