### ISSUE TITLE
loki packages loki-2.0.0+git.1603727260.6978ee5d-5.1 is broken

### ISSUE THREAD

**Issue by pirat013** [SUSE/ha-sap-terraform-deployments#685]
**Used cloud platform**
libvirt 

**Used SLES4SAP version**
SLES15SP2 
- repo: https://download.opensuse.org/repositories/security:/logging/SLE_15_SP2/

**Used client machine OS**
SLES15 SP2 with terraform

**Expected behaviour vs observed behaviour**
the systemd unit for promtail could not be started 
promtail.service - promtail is the agent responsible for gathering logs and sending them to Loki.
   Loaded: loaded (/usr/lib/systemd/system/promtail.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2021-04-26 11:54:50 CEST; 674ms ago
     Docs: https://github.com/grafana/loki/blob/master/docs/promtail.md
  Process: 736 ExecStart=/usr/bin/promtail -config.file=$CONFIG_FILE (code=exited, status=1/FAILURE)
 Main PID: 736 (code=exited, status=1/FAILURE)

**How to reproduce**
The package from the https://download.opensuse.org/repositories/security:/logging/SLE_15_SP2/ repo seams broken because the package from here: https://download.opensuse.org/repositories/network:ha-clustering:sap-deployments:devel//SLE_15_SP2 is working well. 

I've checked the systemd unit files: /usr/lib/systemd/system/promtail.service
The major difference was in this line:
...
ExecStart=/usr/bin/promtail -config.file=${CONFIG_FILE}
...

On the **broken system** is was like this:
...
ExecStart=/usr/bin/promtail -config.file=$CONFIG_FILE
...

After adding the brackets **${CONFIG_FILE}** the systemd unit was working.

**Comment by arbulu89** [comment]
Hi @pirat013 ,
I don't understand why a package failure in OBS is a bug in this project. Why are you using that repository in the first place?
Besides that, `loki` is already shipped in SLES4SAP in the PackageHub module

**Comment by pirat013** [comment]
Hi @arbulu89 ,
I don't know who maintain the repository in OBS. I had this repository already in place and I can't remember the reason. What would you suggest to get in touch with the right person and inform them regarding this issue? All customers who wants to have this packages and if they didn't have a SLES4SAP will may using such kind of sources.

**Comment by pirat013** [comment]
It was just a hint...

**Comment by arbulu89** [comment]
@pirat013 You can find the maintainers of the repository here: https://build.opensuse.org/project/users/security:logging

Anyway, this is an OBS repository, so it means it doesn't have any support from SUSE side. If customers want to use it, it is totally on their risk.

We don't support `loki`, but they can find a copy of the package in PackageHub (again, without customer support).
