### ISSUE TITLE
S/4HANA Netweaver Deployment for GCP in another zone

### ISSUE THREAD

**Issue by busetde** [SUSE/ha-sap-terraform-deployments#697]
Hi, 

When deploying S/4HANA on GCP the zone location for:
- netweaver01 in zone a
- netweaver02 in zone b
- netweaver03 in zone c
- netweaver04 in zone a

Is it possible to change the netweaver03 in zone a (instead of zone c) and netweaver04 in zone b?
References:
https://cloud.google.com/solutions/sap/docs/netweaver-ha-planning-guide

Thanks - Budi

**Comment by yeoldegrove** [comment]
Sorry for the delay. This will be fixed shortly.

**Comment by yeoldegrove** [comment]
fixed in #829
