### ISSUE TITLE
google_compute_subnetwork.ha_subnet is empty tuple

### ISSUE THREAD

**Issue by coreman21** [SUSE/ha-sap-terraform-deployments#704]
I'm having an issue with the GCP portion of this. I'm using terraform version v0.15.4 and when I run terraform apply --var-file terraform-tst1.tfvars I keep getting the same error. 

 Warning: Version constraints inside provider configuration blocks are deprecated
│
│   on infrastructure.tf line 3, in provider "google":
│    3:   version     = "~> 3.43.0"
│
│ Terraform 0.13 and earlier allowed provider version constraints inside the provider configuration block, but that is now deprecated and will
│ be removed in a future version of Terraform. To silence this warning, move the provider version constraint into the required_providers block.
╵
╷
│ Error: Invalid index
│
│   on infrastructure.tf line 126, in resource "google_compute_router_nat" "nat":
│  126:     name                    = google_compute_subnetwork.ha_subnet.*.self_link[0]
│     ├────────────────
│     │ google_compute_subnetwork.ha_subnet is empty tuple
│
│ The given key does not identify an element in this collection value.

It seems to be an issue with the infrastructure.tf, but I don't see anything in the variable file that asks for ha_subnet.

**Comment by arbulu89** [comment]
Hi @coreman21 ,
Please use the provided pattern to create the ticket, we need more additional information.
https://github.com/SUSE/ha-sap-terraform-deployments/issues/new?assignees=arbulu89&labels=bug&template=bug_report.md&title=

**Comment by coreman21** [comment]
Sorry, I was getting this error when running terraform plan under "/ha-sap-terraform-deployments/gcp". 

The issue was solved by setting **bastion_enabled = false**
