### ISSUE TITLE
Automate the deployment of HANA Scale-Out scenario

### ISSUE THREAD

**Issue by stefanotorresi** [SUSE/ha-sap-terraform-deployments#706]
We need to automate the procedure to deploy the "SAP HANA Scale-Out Performance Optimized" scenario explained here: https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/

Most of the main concepts can be applied transparently.

For reference, there is also a [dedicated document for AWS](https://documentation.suse.com/sbp/all/html/SLES-SAP-hana-scaleOut-PerfOpt-12-AWS/index.html), which is more up-to-date, but we actually want to implement Azure first, here.

The implementation was started in #643, but left incomplete. It might be necessary to start from scratch, but that's up to the implementor.

**Comment by yeoldegrove** [comment]
The feature is available with the https://github.com/SUSE/ha-sap-terraform-deployments/releases/tag/9.0.0 release.
