### ISSUE TITLE
Monitoring configuration for ASCS and ERS are not available on all hosts

### ISSUE THREAD

**Issue by pirat013** [SUSE/ha-sap-terraform-deployments#712]
**Used cloud platform**
libvirt

**Used SLES4SAP version**
SLES15SP2

**Used client machine OS**
Linux SLES15 SP2

**Expected behaviour vs observed behaviour**
The Prometheus exporter for the ASCS and ERS can not be started from Pacemaker after a resource swap has happen. After the deployment the ASCS is running on netweaver01 and ERS is running on netweaver02. If the ASCS must start on the netweaver02 node and the ERS is moving to netweaver01 the exporter can not be started because of the profile is missing.

`netweaver01:~ # ls /etc/sap_host_exporter/
default.yaml  H3O_ASCS00.yaml
`
`netweaver02:~ # ls /etc/sap_host_exporter/
default.yaml  H3O_ERS10.yaml
`

**How to reproduce**
Doing a ASCS resource takeover from the initial cluster (were it was installed) node to the second cluster node (initial home of the ERS).

The usage of the `provisioning_log_level = "info"` option in the `terraform.tfvars` file is interesting to get more information during the terraform commands execution. So it is suggested to run the deployment with this option to see what happens before opening any ticket.

**Used terraform.tfvars**
´´

These is the list of the required logs (each of the deployed machines will have all of them):
- /var/log/salt-os-setup.log
- /var/log/salt-predeployment.log
- /var/log/salt-deployment.log
- /var/log/salt-result.log

I'll send the logs privately, please tell which e-mail address I can use.

Thanks Bernd

Additional logs might be required to deepen the analysis on HANA or NETWEAVER installation. They will be asked specifically in case of need.

**Comment by yeoldegrove** [comment]
I also noted this behavior yesterday.

The yaml file is hardcoded in https://github.com/SUSE/sapnwbootstrap-formula/blob/master/netweaver/monitoring.sls#L17.
This is not a file available on all cluster nodes of course.

We would need something of the following:
  - a configurable path in sapnwbootstrap (/etc by default)
    - this could be injected by a grain by salt/terraform
  - something that adds the file in ha-sap-terraform-deployments (redundant code)

**Comment by yeoldegrove** [comment]
fixed in SUSE/sapnwbootstrap-formula#88
