### ISSUE TITLE
Improve documentation with requirements

### ISSUE THREAD

**Issue by ricardobranco777** [SUSE/ha-sap-terraform-deployments#730]
I had to install `xsltproc` in the machine where I was running Terraform to deploy HANA with libvirt.  This requirement should be added to the documentation.

**Comment by melzer-b1** [comment]
@ricardobranco777
Do you know if really xsltproc is needed or only one of it dependencies (libxslt, libxml) was missing for your terraform?

**Comment by ricardobranco777** [comment]
> @ricardobranco777
> Do you know if really xsltproc is needed or only one of it dependencies (libxslt, libxml) was missing for your terraform?

It's the command itself.  Weird.  I tried it from Ubuntu.
