### ISSUE TITLE
"count" usage in TFE

### ISSUE THREAD

**Issue by nasjomach** [SUSE/ha-sap-terraform-deployments#747]
"count" parameter in TFE is not easy to manage as of my understanding.
For example, if one provision 3 systems:
sys1, sys2, sys3 using count.

How do you remove "sys2" ? 
Most probably you cant. One would decrease "count" to 2 and most probably it will want to destroy "sys3"?

Recent version of TFE support for each loops, dynamics, etc.

**Comment by yeoldegrove** [comment]
Currently the project is not really built to be able to change deployments later on.
It is just about the actual deployment currently.
This cannot be changed that easily as a lot of logic is also put into e.g. "position x" in some "count variables".
It would be a nice improvement though of course... But we cannot fix/improve it easily at the moment.
