### ISSUE TITLE
Make the HANA and NW machines hostname configurable

### ISSUE THREAD

**Issue by arbulu89** [SUSE/ha-sap-terraform-deployments#757]
In order to make multiple different deployents, that are not exactly a replica, it would be good to have the option to customize the name if the machines, specially the HANA and NW machine names.

So, for example in the Azure case, instead of having `vmhana01` always, it would be good to have the option to configure the name to `myname01`, etc, keeping the current value as default. The suffix should still be used to number the multiple machines.

**Comment by yeoldegrove** [comment]
The new feature is added with #767.
