### ISSUE TITLE
ClusterLabs HA Multi-Cluster overview dashboard incorrect results

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#781]
**Used cloud platform**
GCP

**Used SLES4SAP version**
SLES15SP2

**Used client machine OS**
Google Cloud Shell

**Expected behavior vs observed behavior**
Expected behavior:  When NetWeaver 7.5 HA cluster is deployed successfully, the `ClusterLabs HA Multi-Cluster Overview` dashboard should shows 100% Up nodes for NetWeaver HA cluster nodes.

Observed behavior: It shows 50% Up nodes for NetWeaver HA cluster nodes.

**How to reproduce**
1. NetWeaver 7.5 normal deployment. 
2. Here are screenshots from the dashboards:
![image](https://user-images.githubusercontent.com/43576598/138078242-3a30221c-de49-44ea-8eed-3bb7cac97c05.png)
![image](https://user-images.githubusercontent.com/43576598/138078323-3f6d1e68-bbbf-4527-aeb8-b4cc1fd2d0fb.png)
3. PAS and AAS are up and running:
```
ha1adm 2> sapcontrol -nr 01 -function GetProcessList
20.10.2021 10:42:07
GetProcessList
OK
name, description, dispstatus, textstatus, starttime, elapsedtime, pid
disp+work, Dispatcher, GREEN, Running, 2021 10 20 08:58:28, 1:43:39, 22253
igswd_mt, IGS Watchdog, GREEN, Running, 2021 10 20 08:58:28, 1:43:39, 22254
gwrd, Gateway, GREEN, Running, 2021 10 20 08:58:29, 1:43:38, 22258
icman, ICM, GREEN, Running, 2021 10 20 08:58:29, 1:43:38, 22259
```
```
ha1adm 4> sapcontrol -nr 02 -function GetProcessList

20.10.2021 10:43:07
GetProcessList
OK
name, description, dispstatus, textstatus, starttime, elapsedtime, pid
disp+work, Dispatcher, GREEN, Running, 2021 10 20 09:01:22, 1:41:45, 17306
igswd_mt, IGS Watchdog, GREEN, Running, 2021 10 20 09:01:22, 1:41:45, 17307
gwrd, Gateway, GREEN, Running, 2021 10 20 09:01:23, 1:41:44, 17311
icman, ICM, GREEN, Running, 2021 10 20 09:01:23, 1:41:44, 17312
```

**Comment by stefanotorresi** [comment]
hmm there should be 4 nodes in total up for netweaver, 2 of which are clustered.
Is node exporter running in the PAS and AAS nodes?

**Comment by ab-mohamed** [comment]
@stefanotorresi I did not check it before destroying the environment. 

What should be the used command to check the node exporter on PAS and AAS?

**Comment by ab-mohamed** [comment]
@yeoldegrove I can't see this fix in the `master` branch. I am still seeing the same reported in https://github.com/SUSE/ha-sap-terraform-deployments/issues/781#issue-1031259562.
