### ISSUE TITLE
Feature Request - GCP NetWeaver and S/4HANA HA Load Balancer

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#783]
**Used cloud platform**
GCP

**Used SLES4SAP version**
Any currently supported version 

**Details**
A feature request to implement the GCP internal load balancer for NetWeaver and S/4HANA  as described in https://cloud.google.com/solutions/sap/docs/netweaver-ha-config-sles.
Currently, the only way to implement NetWeaver or S/4HANA HA cluster is to use the `gcp-vpc-move-route` RA. 

Detailed information can be found in:
* https://cloud.google.com/solutions/sap/docs/netweaver-ha-config-sles#enable-back-end-comms
*  https://cloud.google.com/solutions/sap/docs/netweaver-ha-config-sles#configure_the_failover_support

**Comment by yeoldegrove** [comment]
@ab-mohamed You can try out this new feature in our `development` branch now. Please make sure to use the latest rpms for the drbd, hana, netweaver formulas.

**Comment by ab-mohamed** [comment]
@yeoldegrove Unfortunately, the deployment execution was failed. 

The DRBD cluster was not created successfully, as shown in the attached deployment output logs.

The monitoring server reported only the `default-vmdrbd02` instance as the online node, but there were no configured resource agents, as shown below:
```
default-vmdrbd02:~ # crm_mon -rnf1
Cluster Summary:
  * Stack: corosync
  * Current DC: default-vmdrbd02 (version 2.0.4+20200616.2deceaa3a-3.12.1-2.0.4+20200616.2deceaa3a) - partition with quorum
  * Last updated: Mon Dec  6 11:24:57 2021
  * Last change:  Mon Dec  6 10:04:39 2021 by root via cibadmin on default-vmdrbd02
  * 1 node configured
  * 0 resource instances configured

Node List:
  * Node default-vmdrbd02: online:
    * Resources:

Inactive Resources:
  * No inactive resources

Migration Summary:
```

The DRBD disk was not used:
```
default-vmdrbd02:~ # lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    0  10G  0 disk
├─sda1   8:1    0   2M  0 part
├─sda2   8:2    0  20M  0 part /boot/efi
└─sda3   8:3    0  10G  0 part /
sdb      8:16   0  10G  0 disk
└─sdb1   8:17   0  10G  0 part
```
```
default-vmdrbd02:~ # df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  7.4G  8.0K  7.4G   1% /dev
tmpfs          tmpfs      11G   55M   11G   1% /dev/shm
tmpfs          tmpfs     7.4G  8.8M  7.4G   1% /run
tmpfs          tmpfs     7.4G     0  7.4G   0% /sys/fs/cgroup
/dev/sda3      xfs        10G  2.7G  7.3G  27% /
/dev/sda2      vfat       20M  6.0M   15M  30% /boot/efi
tmpfs          tmpfs     1.5G     0  1.5G   0% /run/user/0
```

And there were no created NFS shares.

I am going to share the following files:
1. `terraform.tfvars`
2. The deployment logs 
3. `supportconfig` file from each instance
4. `/var/log` directory content from each instance

**Comment by yeoldegrove** [comment]
After fixing the monitoring setup in https://github.com/SUSE/hanadb_exporter/pull/101 and https://github.com/SUSE/ha-sap-terraform-deployments/pull/807 I was able to build a setup with the load-balancer setup enabled (new default).

![image](https://user-images.githubusercontent.com/8668070/148925006-f4a4f984-fdb6-461c-a4a9-3fc0e5cb1429.png)
![image](https://user-images.githubusercontent.com/8668070/148925338-324d866b-7b72-4ebe-8986-77da99f274d4.png)

@ab-mohamed Please try again with the latest rpms `ha_sap_deployment_repo = "https://download.opensuse.org/repositories/network:/ha-clustering:/sap-deployments:/devel/"` and the latest `develop` branch.

**Comment by yeoldegrove** [comment]
@ab-mohamed can we close this issue again?

**Comment by yeoldegrove** [comment]
Reopen in case this still happens with `8.0.0` release.
