### ISSUE TITLE
Support for SAP S/4 HANA 2021 version

### ISSUE THREAD

**Issue by picoroma** [SUSE/ha-sap-terraform-deployments#805]
Does the script support to deploy new version of SAP S/4 HANA (2021)?
Or is still supported only version 2020, yet?
THX

**Comment by yeoldegrove** [comment]
@picoroma I got S/4HANA 2020 working with these code changes https://github.com/SUSE/sapnwbootstrap-formula/pull/92 and https://github.com/SUSE/ha-sap-terraform-deployments/pull/808.
Please use the latest `develop` branch of https://github.com/SUSE/ha-sap-terraform-deployments together with ` ha_sap_deployment_repo = "https://download.opensuse.org/repositories/network:/ha-clustering:/sap-deployments:/devel/"`.

S/4HANA 2021 is what I am going to be evaluating next.

**Comment by yeoldegrove** [comment]
I can confirm that S/4HANA 2021 also works with the latest changes.
An update to our `master` branch is outstanding but will happen independently of this issue, unless explicitly requested.
