### ISSUE TITLE
Upgrade code to Terraform v0.12

### ISSUE THREAD

**Issue by ricardobranco777** [SUSE/ha-sap-terraform-deployments#82]
Here's the Changelog with all the syntax and cli changes:
https://github.com/hashicorp/terraform/blob/v0.12.0/CHANGELOG.md

The upgrade guide with a link to a tool to automate most of the process:
https://www.terraform.io/upgrade-guides/0-12.html

We also need to wait for the openSUSE packagers to ship updated versions because of our use of the Terraform libvirt provider:
http://download.opensuse.org/repositories/systemsmanagement:/terraform/

**Comment by MalloZup** [comment]
We will need to change also the terraform `count` variable in future, since it is reserved

```
Error: Reserved argument name in module block

  on main.tf line 21, in module "sbd_disk":
  21:   count              = "${var.shared_storage_type == "shared-disk" ? 1 : 0}"

The name "count" is reserved for use in a future version of Terraform.


Error: Reserved argument name in module block

  on main.tf line 28, in module "iscsi_server":
  28:   count                  = "${var.shared_storage_type == "iscsi" ? 1 : 0}"

The name "count" is reserved for use in a future version of Terraform.


Error: Reserved argument name in module block

  on main.tf line 49, in module "hana_node":
  49:   count                  = 2

The name "count" is reserved for use in a future version of Terraform.
````

**Comment by MalloZup** [comment]
@ricardobranco777  I'm closing this since we have tracked it on trello.

https://trello.com/c/Mb7sgWBD/799-migrate-to-terraform-12

thx!
