### ISSUE TITLE
Master branch for GCP - terraform plan show error

### ISSUE THREAD

**Issue by busetde** [SUSE/ha-sap-terraform-deployments#828]
Hi @yeoldegrove,

Tried the updated master branch for GCP but got error like below while execute terraform plan as below.
Could you kindly advise what's wrong, as I've tried the previous develop branch it's not shows error when run terraform plan?

![image](https://user-images.githubusercontent.com/63712632/157820159-85407739-db0f-4d8a-ae88-fa5b8ab118f7.png)

Regards - Budi

**Comment by yeoldegrove** [comment]
@busetde I could not reproduce this error with a cleanly cloned master branch and a `cp terraform.tfvars.example terraform.tfvars`.
Are you sure you are using the latest master commit?

**Comment by busetde** [comment]
Hi @yeoldegrove,

I've just done the below
-Clone from master branch
`git clone -b master https://github.com/SUSE/ha-sap-terraform-deployments.git`
-Copy previous working terraform.tfvars 
-Run `terraform plan` the same error like below:
![image](https://user-images.githubusercontent.com/63712632/158388719-d3115f2a-728d-409a-aaf9-d550c8270be6.png)



-Run `terraform plan` from the previously working develop branch, there's no error like below:
![image](https://user-images.githubusercontent.com/63712632/158388365-dc3ed1cf-1fde-4f6c-a865-6efd667b005a.png)


Could you please kindly advise on what I need to check?

Appreciated - Budi

**Comment by yeoldegrove** [comment]
@busetde Could you share a redacted `terraform.tfvars`?

**Comment by busetde** [comment]
@yeoldegrove 

Please find the redacted `terraform.tfvars`
[terraform.tfvars.txt](https://github.com/SUSE/ha-sap-terraform-deployments/files/8254126/terraform.tfvars.txt)

Regards - Budi

**Comment by yeoldegrove** [comment]
Found the issue... When updating the GCP code to the latest terraform provider, we forgot to test the deployment without a bastion and hence the firewall resources are missing `source_ranges = ["0.0.0.0/0"]`.
#830 fixes this.

**Comment by busetde** [comment]
@yeoldegrove 

Could you please kindly advise if I can test this from the master branch?

Regards - Budi

**Comment by yeoldegrove** [comment]
@busetde It is available in `develop` already. I plan to release 8.0.1/master today/tomorrow.

**Comment by yeoldegrove** [comment]
@busetde https://github.com/SUSE/ha-sap-terraform-deployments/releases/tag/8.0.1 hast just released, including fixes for this issue
