### ISSUE TITLE
DEPLOY NW750.HDB.ABAP - ERROR  with EFS

### ISSUE THREAD

**Issue by picoroma** [SUSE/ha-sap-terraform-deployments#833]
**Used cloud platform**
AWS

**Used SLES4SAP version**
SLES15SP2

**Used client machine OS**
Windows10

**Expected behaviour vs observed behaviour**
Deploy of Netweaver fails with error:

Rendering SLS 'predeployment:shared_storage.nfs' failed: mapping values are not allowed in this context[0;0m
[0;31mFri Mar 18 10:08:24 UTC 2022::ip-10-0-2-7::[ERROR] predeployment failed [0m

**Comment by yeoldegrove** [comment]
@picoroma  https://github.com/SUSE/ha-sap-terraform-deployments/releases/tag/8.0.1 hast just released, including fixes for this issue.
It would be cool if you could confirm that it works now.

**Comment by yeoldegrove** [comment]
actual fix was merged in #834

**Comment by picoroma** [comment]
Deploy still fiish with error:
-
module.netweaver_node.module.netweaver_provision.null_resource.provision[0] (remote-exec): [INFO    ] Executing command 'mkswap' in directory '/root'
╷
│ Error: remote-exec provisioner error
│
│   with module.hana_node.module.hana_provision.null_resource.provision[0],
│   on ..\generic_modules\salt_provisioner\main.tf line 78, in resource "null_resource" "provision":
│   78:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_1101107392.sh": wait: remote command exited without exit status or exit signal
╵
╷
│ Error: remote-exec provisioner error
│
│   with module.netweaver_node.module.netweaver_provision.null_resource.provision[0],
│   on ..\generic_modules\salt_provisioner\main.tf line 78, in resource "null_resource" "provision":
│   78:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_272281190.sh": wait: remote command exited without exit status or exit signal

In the salt-deployment.log file of Netweaver I have:
[ERROR   ][2944] Specified path /sapmnt/HA1/profile does not exist
2022-03-23 17:37:10,033 [salt.state       :2259][INFO    ][2944] Completed state [/sapmnt/HA1/profile] at time 17:37:10.033508 (duration_in_ms=1.972)
2022-03-23 17:37:10,033 [salt.state       :2274][INFO    ][2944] State result does not match retry until value, state will be re-run in 30 seconds
2022-03-23 17:37:40,045 [salt.state       :2065][INFO    ][2944] Running state [/sapmnt/HA1/profile] at time 17:37:40.045022
2022-03-23 17:37:40,046 [salt.state       :2097][INFO    ][2944] Executing state file.exists for [/sapmnt/HA1/profile]
2022-03-23 17:37:40,047 [salt.state       :322 ][ERROR   ][2944] Specified path /sapmnt/HA1/profile does not exist
2022-03-23 17:37:40,047 [salt.state       :2259][INFO    ][2944] Completed state [/sapmnt/HA1/profile] at time 17:37:40.047588 (duration_in_ms=2.567)

HANA installation finish at least 5-10 min after the deploy ended with error. THis is quite strange...

**Comment by yeoldegrove** [comment]
@picoroma The HANA nodes can take longer than netweaver01/02, this is fine, as the do not need the DB.
`Specified path /sapmnt/HA1/profile does not exist` is also fine. It is just a check that is being executed in a loop on the ERS/PAS/AAS to find out if the ASCS is installed.

Could you send over all the `/var/log/salt*` logs from all the nodes?

**Comment by picoroma** [comment]
Hi! I have tried even with a PAYG OS Image. I have  even in this case an error.
I have the log file - Do you have an email address where I can send it (due to sensitive data) ?

**Comment by yeoldegrove** [comment]
@picoroma Closing this as I had multiple successful EFS NW deployments in the meantime.
We're happy to investigate/reopen if you still have this issue.
