### ISSUE TITLE
Variables and secrets exposed at /etc/salt/grains

### ISSUE THREAD

**Issue by abravosuse** [SUSE/ha-sap-terraform-deployments#862]
The variables and secrets set in the terraform.tfvars file are exposed in plain text file /etc/salt/grains, including master passwords. Even though folder /etc/salt can only be accessed by root or members of the salt group, this is a vulnerability and it would be preferable if the file was removed altogether at some point during the execution process.

**Comment by yeoldegrove** [comment]
@melzer-b1 What do you think? Could be implement another switch in `terraform.tfvars` e.g. `cleanup_secrets = true` which is enabled by default?

**Comment by yeoldegrove** [comment]
@abravosuse #877 is a suggestion on how to implement this feature. Any other suggestions which files to e.g. delete?

**Comment by abravosuse** [comment]
> @abravosuse #877 is a suggestion on how to implement this feature. Any other suggestions which files to e.g. delete?

It looks good to me, Eike. Thanks!

**Comment by yeoldegrove** [comment]
implemented in #877
