### ISSUE TITLE
Corosync settings on AWS 

### ISSUE THREAD

**Issue by stephenmogg** [SUSE/ha-sap-terraform-deployments#867]
Is it possible to validate the values used during configuration of the cluster on AWS.
I deployed 2 weeks ago, and found things like the token and consensus values seemed to be set at older best practice setting values.

The current best practice values can be found here ...
https://docs.aws.amazon.com/sap/latest/sap-hana/sap-hana-on-aws-cluster-configuration.html

May be worth checking the timeouts for the SAP resources too.
https://docs.aws.amazon.com/sap/latest/sap-hana/sap-hana-on-aws-cluster-resources.html

If you need specifics, let me know.

**Comment by yeoldegrove** [comment]
@stephenmogg 

https://docs.aws.amazon.com/sap/latest/sap-hana/sap-hana-on-aws-cluster-configuration.html mentions:
```
        token: 30000
        consensus: 36000
```

Something similar to https://github.com/SUSE/ha-sap-terraform-deployments/blob/8f3cc1846638d661c3fec3a714cd84de5fd7abf3/pillar_examples/automatic/netweaver/cluster.sls#L34-L41 would be needed.

Are you up to do a commit or shall I take over?

After a first look, I would say that the resource timeouts are fine.

**Comment by yeoldegrove** [comment]
@stephenmogg ping?

**Comment by stephenmogg** [comment]
Hi,  Yes I'll try and submit this week.

**Comment by yeoldegrove** [comment]
For completeness, the SUSE reference: https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-perfopt-15-aws/index.html#id-1.11.6.5.6

**Comment by yeoldegrove** [comment]
fixed in #869
