### ISSUE TITLE
No Top file or master_tops data matches found

### ISSUE THREAD

**Issue by tstaerk** [SUSE/ha-sap-terraform-deployments#874]
**Used cloud platform**
GCP

**Used SLES4SAP version**
SLES15SP2

**Used client machine OS**
ChromeOS

**Expected behaviour vs observed behaviour**
Expected behavior: When I type terraform apply, I do not expect an error message
Actual behavior: When I type terraform appy, I get the message

module.hana_node.module.hana_provision.null_resource.provision[1]: Still creating... [7m20s elapsed]
module.hana_node.module.hana_provision.null_resource.provision[0]: Still creating... [7m20s elapsed]
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): Connecting to remote host via SSH...
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Host: 35.187.177.151
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   User: root
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Password: false
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Private key: true
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Certificate: false
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   SSH Agent: false
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Checking Host Key: false
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Target Platform: unix
module.hana_node.module.hana_provision.null_resource.provision[0]: Still creating... [7m30s elapsed]
module.hana_node.module.hana_provision.null_resource.provision[1]: Still creating... [7m30s elapsed]
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): Connecting to remote host via SSH...
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   Host: 35.233.4.64
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   User: root
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   Password: false
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   Private key: true
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   Certificate: false
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   SSH Agent: false
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   Checking Host Key: false
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):   Target Platform: unix
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): Connected!
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): [INFO    ] Loading fresh modules for state activity
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): local:
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): ----------
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):           ID: states
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):     Function: no.None
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):       Result: False
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Comment: No Top file or master_tops data matches found. Please see master log for details.
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):      Changes:   
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec):
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): Summary for local
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): ------------
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): Succeeded: 0
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): Failed:    1
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): ------------
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): Total states run:     1
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): Total run time:   0.000 ms
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): Wed Jul 20 08:01:35 UTC 2022::demo-hana02::[ERROR] predeployment failed 
module.hana_node.module.hana_provision.null_resource.provision[0]: Still creating... [7m40s elapsed]
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): Connecting to remote host via SSH...
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Host: 35.187.177.151
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   User: root
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Password: false
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Private key: true
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Certificate: false
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   SSH Agent: false
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Checking Host Key: false
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):   Target Platform: unix
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): Connected!
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): [INFO    ] Loading fresh modules for state activity
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): local:
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): ----------
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):           ID: states
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):     Function: no.None
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):       Result: False
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):      Comment: No Top file or master_tops data matches found. Please see master log for details.
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):      Changes:   
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec):
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): Summary for local
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): ------------
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): Succeeded: 0
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): Failed:    1
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): ------------
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): Total states run:     1
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): Total run time:   0.000 ms
module.hana_node.module.hana_provision.null_resource.provision[0]: Still creating... [7m50s elapsed]
module.hana_node.module.hana_provision.null_resource.provision[0] (remote-exec): Wed Jul 20 08:01:45 UTC 2022::demo-hana01::[ERROR] predeployment failed 
╷
│ Error: remote-exec provisioner error
│
│   with module.hana_node.module.hana_provision.null_resource.provision[0],
│   on ../generic_modules/salt_provisioner/main.tf line 78, in resource "null_resource" "provision":
│   78:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_789437939.sh": Process exited with status 1
╵
╷
│ Error: remote-exec provisioner error
│
│   with module.hana_node.module.hana_provision.null_resource.provision[1],
│   on ../generic_modules/salt_provisioner/main.tf line 78, in resource "null_resource" "provision":
│   78:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_1561301982.sh": Process exited with status 1

**How to reproduce**
Specify the step by step process to reproduce the issue. This usually would look like something like this:

1. Move to any of the cloud providers folder
2. Create the `terraform.tfvars` file based on `terraform.tfvars.example`
3. Run the next terraform commands:
  ```
  terraform init
  terraform plan
  terraform apply -auto-approve
  ```

The usage of the `provisioning_log_level = "info"` option in the `terraform.tfvars` file is interesting to get more information during the terraform commands execution. So it is suggested to run the deployment with this option to see what happens before opening any ticket.

**Used terraform.tfvars**
Paste here the used `terraform.tfvars` file content. If the file has any secret, change them by dummy information.

**Logs**
Upload the deployment logs to make the root cause finding easier. **The logs might have sensitive secrets exposed. Remove them before uploading anything here. Otherwise, contact @arbulu89 to send the logs privately**.

These is the list of the required logs (each of the deployed machines will have all of them):
- /var/log/salt-os-setup.log
- /var/log/salt-predeployment.log
- /var/log/salt-deployment.log
- /var/log/salt-result.log

Additional logs might be required to deepen the analysis on HANA or NETWEAVER installation. They will be asked specifically in case of need.

**Comment by tstaerk** [comment]
I was just pasting the error message and the bug became auto-submitted. So I still want to add to the description:
* where is this master log the error message is talking about?
* I wrote a 24 pages document how I produced this error message, it is here: https://docs.google.com/document/d/1LP-10QtJ7aIqEK-r-3kwjmYUb00h-XjpDaqyAU3-vGc/edit#

**Comment by yeoldegrove** [comment]
@tstaerk I would need to have the exact release version (or git commit) you used for your deployment.

Version `8.1.3` and later include this fix which solved similar issues for me. 
https://github.com/SUSE/ha-sap-terraform-deployments/compare/8.1.2...8.1.3#diff-72f855c338d037a9b865eb5c03ecd8448e89776aba3a4549bbd8950a584d8c2f

**Comment by tstaerk** [comment]
oh, sorry, correct, Ab told me to update, but I forgot as I started a new project. Leave it to me, I guess I'll confirm soon.

**Comment by yeoldegrove** [comment]
Please reopen in case the issue still occurs.
