### ISSUE TITLE
iscsi terraform output is not the same for all providers

### ISSUE THREAD

**Issue by mpagot** [SUSE/ha-sap-terraform-deployments#876]
**Used cloud platform**
Azure

**Used SLES4SAP version**
Not relevant

**Used client machine OS**
Linux (openSUSE TW)

**Expected behaviour vs observed behaviour**
Problem is in **iscsi_srv_ip**

Observed:
```
terraform -chdir=terraform/azure output -json|grep iscsi|grep srv
  "iscsi_srv_ip": {
  "iscsisrv_name": {
  "iscsisrv_public_ip": {
  "iscsisrv_public_name": {
```

Expected:
```
terraform -chdir=terraform/azure output -json|grep iscsi|grep srv
  "iscsisrv_ip": {
  "iscsisrv_name": {
  "iscsisrv_public_ip": {
  "iscsisrv_public_name": {
```

**How to reproduce**

3. Run the next terraform commands for Azure :
  ```
  terraform init
  terraform plan
  terraform apply -auto-approve
terraform output -json|grep iscsi|grep srv
  ```

**Used terraform.tfvars**
Not relevant

**Logs**
Not available

**Comment by yeoldegrove** [comment]
It would be a good idea to revisit all the terraform outputs. I also found some of them confusing. e.g. `cluster_nodes` makes no sense anymore as multiple clusters are deployed.

**Comment by yeoldegrove** [comment]
@melzer-b1 Please come up with some ideas what to change.

**Comment by yeoldegrove** [comment]
All outputs have been completely reworked in #893
