### ISSUE TITLE
GCP  fence_gce location constrains

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#887]
**Used cloud platform**
GCP

**Used SLES4SAP version**
SLES12|15 SPx

**Used client machine OS**
macOS

**Expected behaviour vs observed behaviour**
`fence_gce` location constraints are not configured as documented in https://cloud.google.com/solutions/sap/docs/netweaver-ha-config-sles#create_the_fencing_device_resources

**How to reproduce**
1. Default deployment
2. Execute the following commands:
```
# crm configure location <FENCING_LOCATION_NAME_PRIMARY_VM> \
  <FENCING_RESOURCE_PRIMARY_VM> -inf: <PRIMARY_VM_NAME>
```
```
# crm configure location <FENCING_LOCATION_NAME_SECONDARY_VM> \
  <FENCING_RESOURCE_SECONDARY_VM> -inf: <SECONDARY_VM_NAME>
```

**Comment by yeoldegrove** [comment]
This needs to be fixed in https://github.com/SUSE/saphanabootstrap-formula.

**Comment by yeoldegrove** [comment]
https://github.com/SUSE/saphanabootstrap-formula/pull/148 will fix this
