### ISSUE TITLE
SAP HANA 2.0 SPS 07 won't install

### ISSUE THREAD

**Issue by tuttipazzo** [SUSE/ha-sap-terraform-deployments#906]
**Used cloud platform**
Specify the used cloud platform (AWS, GCP, Azure, etc)
Azure

**Used SLES4SAP version**
Specify the used SLES4SAP version (SLES12SP4, SLES15SP2, etc)
SLES15SP4

**Used client machine OS**
Specify the used machine OS to execute the project (Windows, any Linux distro, macOS).
Even though terraform is multi-platform, some of the local actions are based in Linux distributions, so some operations might fail for this reason.
SLES15SP4

**Expected behaviour vs observed behaviour**
Describe with details what is the faced issue during the usage of the project, and what would be the expected result. If the error is just that `I cannot make the project work, it always fails` specify the next chapters information so we can understand in which point the project fails.

It fails with the following msg from (hdblcm.log):
20:27:24.671 - ERR :   Running in batch mode
20:27:24.610 - ERR :     Installation of SAP HANA Local Secure Store is possible only in optimized execution mode

**How to reproduce**
Specify the step by step process to reproduce the issue. This usually would look like something like this:

1. Take a working Azure terraform.tfvars and change hana_inst_master from 
           hana_inst_master = "//pazzosa.file.core.windows.net/51055101"
     to
           hana_inst_master = "//pazzosa.file.core.windows.net/51056451" 

I always run with 
                                  provisioning_log_level = "debug"

**Used terraform.tfvars**
Paste here the used `terraform.tfvars` file content. If the file has any secret, change them by dummy information.
az_region = "westus2"
resource_group_name = "pazzorg"
admin_user = "pazzo"
reg_code = "XXXXXXXX-XXX-XXXX-YYYY-YYYY"
reg_email = "pazzo@thatcrazyItaliancountry.com"
os_image = "SUSE:sles-sap-15-sp4-byos:gen2:latest"
public_key  = "/home/pazzo/.ssh/suse.pub"
private_key = "/home/pazzo/.ssh/suse"
cluster_ssh_pub = "salt://sshkeys/cluster.id_rsa.pub"
cluster_ssh_key = "salt://sshkeys/cluster.id_rsa"
ha_sap_deployment_repo = "https://download.opensuse.org/repositories/network:ha-clustering:sap-deployments:v9/"
provisioning_log_level = "debug"
pre_deployment = true
bastion_enabled = false
hana_name = "vmhana"
hana_vm_size = "Standard_DS12-2_v2"
hana_count = "2"
hana_os_image = "SUSE:sles-sap-15-sp4-byos:gen2:latest"
storage_account_name = "pazzosa"
storage_account_key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
hana_inst_master = "//pazzosa.file.core.windows.net/51056451"
hana_inst_folder = "/sapmedia/HANA"
hana_ha_enabled = true
hana_instance_number = "00"
hana_master_password = "Poopy123!"
hana_primary_site = "cow"
hana_secondary_site = "sheep"
iscsi_name = "vmiscsi"
iscsi_os_image = "SUSE:sles-sap-15-sp4-byos:gen2:latest"

**Logs**
Upload the deployment logs to make the root cause finding easier. **The logs might have sensitive secrets exposed. Remove them before uploading anything here. Otherwise, contact @arbulu89 to send the logs privately**.

Ping me privately and I will upload logs.

These is the list of the required logs (each of the deployed machines will have all of them):
- /var/log/salt-os-setup.log
- /var/log/salt-predeployment.log
- /var/log/salt-deployment.log
- /var/log/salt-result.log

Additional logs might be required to deepen the analysis on HANA or NETWEAVER installation. They will be asked specifically in case of need.

**Comment by mr-stringer** [comment]
Hi, can we connect over slack so you can send me the files?

**Comment by yeoldegrove** [comment]
@mr-stringer @tuttipazzo Please try out the new `hana_extra_parameters` option added in #907. It allows me to install a HANA 2.0 SPS07 rev70.

**Comment by yeoldegrove** [comment]
https://github.com/SUSE/ha-sap-terraform-deployments/releases/tag/9.1.0 was just released which fixes the issue.
@tuttipazzo Please reopen if you are still facing issues.

**Comment by tuttipazzo** [comment]
Thanks.
