### ISSUE TITLE
NEW Feature: Implement susTkOver, susChkSrv, & susCostOpt srHooks

### ISSUE THREAD

**Issue by tuttipazzo** [SUSE/ha-sap-terraform-deployments#910]
**Used cloud platform**
AWS, GCP, Azure, libvirt

**Used SLES4SAP version**
SLES15.SPx

**Used client machine OS**
Leap/TW

**Expected behaviour vs observed behaviour**
Nothing is failing.  These new hooks should be included.

**How to reproduce**
N/A

**Logs**
N/A

**Comment by yeoldegrove** [comment]
The hook should be integrated in https://github.com/SUSE/saphanabootstrap-formula.
Maybe one could think about an interface/switch to enable/disable certain hooks.

**Comment by tuttipazzo** [comment]
I see susTkOver from 2-node cluster I deployed back in late September.  I had to manually add susChksrv so that's missing.  But I agree with yeoldegrove that there needs ot be a switch to turn on/off some of the hooks.

**Comment by yeoldegrove** [comment]
@tuttipazzo https://github.com/SUSE/ha-sap-terraform-deployments/releases/tag/9.2.0 lets you define the following in `terraform.tfvars`:
```
# HANA HA/DR provider configuration
# See https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/#cha.s4s.hana-hook for details.
# The SAPHanaSR hook is always enabled.
# enable susTkOver hook (disabled by default)
# hana_ha_dr_sustkover_enabled = true
# enable susChkSrv hook (disabled by default)
# hana_ha_dr_suschksrv_enabled = true
# susChkSrv action on lost, see `man 7 susChkSrv.py` (Options: stop [default], fence)
# hana_ha_dr_suschksrv_action_on_lost = "fence"
```

This solves your use case.
