### ISSUE TITLE
find out a more effective way to deploy to libvirt/kvm when we have low bandwith

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#92]
# Problem:

I don't have much bandwith for deploying to the central deplyement server.

I deploy from France `terraform apply` to `NUE` KVM server where we can deploy.

Deploying this way take times, especially for copying from France to NUE the images.

( there is no way that we can do it on the terraform-libvirt-kvm, I have already researched).

Currently if the `base-image` exists, we prompt out and error out that resource already exists.

We need to research a way to create a global shared image that it is created, and used in a `cached` way

# Technical implementation:

This problem can be solved in many ways. 

 1) create a terraform `null_resource` which execute a script for checking that the image already exist and is the latest one, otherwise recreate/download the lates.
 
2) it could be also a crontab job running on the server which download and create the shared img and the terraform files depends explitely from that.

For solution 2, we should create like  a special `golum` directory terraform files, which we state that we depends from that img beeing create by x custom script

3) an other implementations ..

**Comment by diegoakechi** [comment]
@MalloZup Don't you think that the libvirt provider plugin should handle such intelligence? It seems an interesting feature for it.

**Comment by MalloZup** [comment]
@diegoakechi yep,  I remember to have spoken time ago with @inercia when we were doing some caasp thing, we discussed it longtime but the Libvirt API doesn't provide such call :cry:

**Comment by MalloZup** [comment]
a current limitation on provider is this one: https://github.com/dmacvicar/terraform-provider-libvirt/issues/613

**Comment by MalloZup** [comment]
I'm closing for moment this, since i fixed it internally and given our prio we will never do it. It has less prio closing
