### ISSUE TITLE
name_prefix should be removed

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#93]
# Problem/desc:

we have currenlty `name-prefix` as tfvars.

https://github.com/SUSE/ha-sap-terraform-deployments/search?q=name_prefix&unscoped_q=name_prefix

We don't need this variable since we can take it form the `workspace` name as we did in past.

e.g see: https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/libvirt/terraform/modules/base/main.tf#L6

**Comment by arbulu89** [comment]
Hey @MalloZup ,
This change is already done, isn't it? `name-prefix` is only used internally now.
In that case we can close the issue.

**Comment by MalloZup** [comment]
Ah yes right let close it for moment
