### ISSUE TITLE
Can't use public SAP images on the salted GCP configuration

### ISSUE THREAD

**Issue by ricardobranco777** [SUSE/ha-sap-terraform-deployments#97]
Currently, the salted configuration for GCP doesn't support public images, so it's useful only for testing.  

The non-salted configuration supports the `use_custom_image` variable for this.

**Comment by ldevulder** [comment]
Agree, this is something that can be improved. Maybe better than using a dedicated variable like this for this, we can use the method used for Azure in the salt version: "If custom uris are enabled public information will be omitted".

So if `sles4sap_public` is set and also `sles4sap_uri` the last one will be used.

Note: I think it could be also a good idea to try to have the same variable name across the provider :)

**Comment by ldevulder** [comment]
You can set `sles4sap_boot_image` to a public image like `suse-byos-cloud/sles-15-sap-byos` for example.

So I think this is what you want, no?
